//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

/**
* Whether TestFlight is reporting on the craft's engines, published on
* `testflight.reliability` whenever TestFlight is installed.
*
* The bound and unbound member lists are the provenance record: a TestFlight
* release that renames a member the reader reflects on shows up here without
* another decompile.
*/
export interface TestFlightReliabilitySummary
{
	/**
	* `modeled` when each engine's part status can be read, or `indeterminate`
	* when not even that bound. A partly-bound reader stays `modeled`: missing
	* rated-time reads only leave the budgets out.
	*/
	coverage?: string | null;
	/** The TestFlight members the reader resolved this session. */
	boundMembers?: string[] | null;
	/** The TestFlight members the reader looked for and did not find. */
	unboundMembers?: string[] | null;
}
/**
* One live TestFlight core aboard the craft: the flying engine config of a
* part, never one of the other configs an RO part carries. Published on
* `testflight.reliabilityParts`.
*/
export interface TestFlightReliabilityPart
{
	/**
	* `"<flightID>:<occurrence>"`, unique within one payload and the id
	* `testflight.repair` addresses: one part can carry more than one live core.
	*/
	partId?: string | null;
	/** The part's title. */
	title?: string | null;
	/**
	* The flying engine config's alias, which is the engine's identity under RO
	* where the part title is not.
	*/
	configuration?: string | null;
	/**
	* `nominal`, `failed` or `unknown`, off TestFlight's own part status.
	* TestFlight grades no failure as more severe than another, so there is no
	* critical class, and an unread status is `unknown`, never `nominal`.
	*/
	condition?: string | null;
	/**
	* The titles of the part's active failures, as TestFlight names them ("Loss of
	* Thrust"), or null when there are none.
	*/
	conditionDetail?: string | null;
	/**
	* The chance the engine survives
	* `TestFlightReliabilityPart.survivalHorizonSeconds` of operation at its
	* current flight data, asked of TestFlight's own reliability curve. Null
	* whenever either input could not be read.
	*/
	survival?: Value<"ratio"> | null;
	/**
	* The span `TestFlightReliabilityPart.survival` is over: the rated cumulative
	* burn, which is the horizon TestFlight's own window quotes it at.
	*/
	survivalHorizonSeconds?: Value<"s"> | null;
	/**
	* The rated burn times, continuous and cumulative, as independent budgets.
	* Only one is sent when the two ratings are equal.
	*/
	budgets?: TestFlightReliabilityBudget[] | null;
	/**
	* How far up its reliability curve this engine config has climbed, in
	* TestFlight's data units.
	*/
	flightData?: Value<"1"> | null;
}
/**
* One rated burn allowance. Past its rating an engine's failure chance climbs
* along a config-authored curve: nothing stops and nothing is guaranteed.
*/
export interface TestFlightReliabilityBudget
{
	/** `burn.continuous` or `burn.cumulative`. */
	id?: string | null;
	/**
	* The lower-case noun an operator reads, naming its scope so neither rating
	* can be read as the other.
	*/
	label?: string | null;
	/** `risk-ramp`. */
	kind?: string | null;
	/**
	* Used over limit, past one once the engine runs beyond its rating. Null when
	* the run time could not be read.
	*/
	consumed?: Value<"ratio"> | null;
	/**
	* Rated seconds used. TestFlight wears an engine thrust-weighted, so these are
	* not seconds of burn at partial throttle.
	*/
	usedSeconds?: Value<"s"> | null;
	/** The rated allowance, in the same seconds. */
	limitSeconds?: Value<"s"> | null;
}
/**
* `testflight.repair`'s args: which engine. TestFlight's repair takes no crew,
* no consumable and no time, so the part is all it needs.
*/
export interface TestFlightRepairPartArgs
{
	/** The engine, by the id `testflight.reliabilityParts` gives it. */
	partId: string;
}
/** What one TestFlight repair did. */
export interface TestFlightRepairOutcome
{
	/** Whether TestFlight cleared the failures it was asked to. */
	repaired: boolean;
	/**
	* How many failures the repair cleared. A terminal failure alongside them
	* stays.
	*/
	failuresCleared: Value<"count">;
}
