//     This code was generated by the Sitrep contract error-code codegen
//     (Sitrep.Contract.RtConfig.EmitErrorCodeMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type { ErrorCodeDeclaration } from "@ksp-gonogo/sitrep-sdk";

/**
 * Why TestFlight refused a repair, each refining the root a client classifies
 * it by. TestFlight's repair checks no crew, consumable or situation, so these
 * are the only answers it can give.
 *
 * @category Error codes
 */
export const TestFlightErrorCodes = {
  /**
   * TestFlight is installed and the reader could not reach its repair or
   * failure-list members.
   */
  NotModelled: "testflight.notModelled",
  /**
   * No live TestFlight core aboard has that id.
   */
  NoSuchPart: "testflight.noSuchPart",
  /**
   * The engine is tracked and carries no active failure.
   */
  NothingFailed: "testflight.nothingFailed",
  /**
   * Every active failure on the engine is a class TestFlight says no repair can
   * fix: an explosion, a fired docking clamp, a snapped solar mechanism.
   */
  Unrepairable: "testflight.unrepairable",
  /**
   * TestFlight was asked to repair and left the failure standing without saying
   * why.
   */
  RepairDeclined: "testflight.repairDeclined",
} as const;
export type TestFlightErrorCodes = (typeof TestFlightErrorCodes)[keyof typeof TestFlightErrorCodes];

/**
 * Every code declared here, with the sentence an operator reads for it.
 *
 * @category Error codes
 */
export const TESTFLIGHT_ERROR_CODES: readonly ErrorCodeDeclaration[] = [
  {
    id: "testflight.notModelled",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "TestFlight is not reporting failures for that engine",
    meaning: "TestFlight is installed and the reader could not reach its repair or failure-list members.",
  },
  {
    id: "testflight.noSuchPart",
    kind: "refusal",
    refines: "notFound",
    origin: null,
    sentence: "no engine TestFlight is tracking has that id",
    meaning: "No live TestFlight core aboard has that id.",
  },
  {
    id: "testflight.nothingFailed",
    kind: "refusal",
    refines: "notFound",
    origin: null,
    sentence: "that engine has no active TestFlight failure",
    meaning: "The engine is tracked and carries no active failure.",
  },
  {
    id: "testflight.unrepairable",
    kind: "refusal",
    refines: "capabilityMismatch",
    origin: null,
    sentence: "TestFlight marks that failure as beyond repair",
    meaning: "Every active failure on the engine is a class TestFlight says no repair can fix: an explosion, a fired docking clamp, a snapped solar mechanism.",
  },
  {
    id: "testflight.repairDeclined",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "TestFlight left the failure standing",
    meaning: "TestFlight was asked to repair and left the failure standing without saying why.",
  },
];
