//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';
import { PayloadMeta } from '@ksp-gonogo/sitrep-sdk';

/**
* One entry of a chain as the OPERATOR SENDS it: a target, and nothing about
* when to use it. Position in the chain is what says when.
*
* This is the mode-and-parameters half of `RealAntennasTargetArgs` with the
* antenna taken off, because an entry names a place to aim and the chain names
* the antenna that aims there. Which of the optional fields are read depends
* on `RealAntennasTargetStepArgs.mode`, and a field the mode does not read is
* ignored rather than refused, exactly as for the single-target command.
*
* **There is no "home" entry, and none is needed.** `BodyCenter` with no
* `RealAntennasTargetStepArgs.bodyName` is the home body's centre, the same
* aim point `realantennas.antenna.targetHome` produces.
*
* **It has a read-side twin, `RealAntennasTargetStep`, and the split is the
* same one the single-target command already makes.** A write shape carries
* plain numbers, because a client builds it and it goes straight onto the
* wire; a read shape carries each number with its unit, because a client
* renders it. Which is why this pair reads exactly like
* `RealAntennasTargetArgs` beside `RealAntennasAntennaState`'s target fields.
*/
export interface RealAntennasTargetStepArgs
{
	/**
	* One of `Vessel`, `BodyCenter`, `BodyLatLonAlt`, `AzEl`, `OrbitRelative`.
	* Anything else is refused, and it is refused for the WHOLE chain rather than
	* for the entry: a chain accepted with one unusable entry in it would silently
	* skip a fallback the operator is relying on.
	*/
	mode: string;
	/** The vessel to point at, for `Vessel`. Ignored by every other mode. */
	vesselId?: string;
	/** The body, for `BodyCenter` and `BodyLatLonAlt`. Empty means the home body. */
	bodyName?: string;
	/** Latitude (degrees, -90..90), for `BodyLatLonAlt`. */
	latitude?: number;
	/** Longitude (degrees, -180..360), for `BodyLatLonAlt`. */
	longitude?: number;
	/**
	* Altitude above the surface (metres), for `BodyLatLonAlt`. Omitted means the
	* surface.
	*/
	altitude?: number;
	/** Azimuth (degrees, 0..360), for `AzEl`. */
	azimuth?: number;
	/** Elevation (degrees, -90..90), for `AzEl` and `OrbitRelative`. */
	elevation?: number;
	/** Deflection from prograde (degrees, -180..180), for `OrbitRelative`. */
	forward?: number;
}
/**
* One entry of a chain as the CRAFT REPORTS it, on
* `realantennas.antennaChains`. Field for field the same target as
* `RealAntennasTargetStepArgs`, which is what the operator sent.
*
* Every number here arrives with its unit, because this side is read and
* rendered. That is the only difference between the two, and it is why there
* are two: see the write twin for the rule.
*/
export interface RealAntennasTargetStep
{
	/**
	* The target's mode: `Vessel`, `BodyCenter`, `BodyLatLonAlt`, `AzEl` or
	* `OrbitRelative`.
	*
	* It comes back as the operator sent it, including `BodyCenter`, which is NOT
	* how RealAntennas stores the target it lowers to. This is the chain the craft
	* is holding rather than a reading of the antenna, and a chain is what was
	* asked for.
	*/
	mode: string;
	/** The vessel to point at, for `Vessel`. Null for every other mode. */
	vesselId?: string;
	/** The body, for `BodyCenter` and `BodyLatLonAlt`. Null means the home body. */
	bodyName?: string;
	/** Latitude (degrees), for `BodyLatLonAlt`. */
	latitude?: Value<"°"> | null;
	/** Longitude (degrees), for `BodyLatLonAlt`. */
	longitude?: Value<"°"> | null;
	/** Altitude above the surface (metres), for `BodyLatLonAlt`. */
	altitude?: Value<"m"> | null;
	/** Azimuth (degrees), for `AzEl`. */
	azimuth?: Value<"°"> | null;
	/** Elevation (degrees), for `AzEl` and `OrbitRelative`. */
	elevation?: Value<"°"> | null;
	/** Deflection from prograde (degrees), for `OrbitRelative`. */
	forward?: Value<"°"> | null;
}
/**
* Args for `realantennas.antenna.targetChain`: hand one antenna an ordered
* list of targets, to be tried in order whenever the craft has no link.
*
* Sending an EMPTY list clears the chain, which is the only way to stop a
* walk. There is no second command for it: a clear is the same operator
* decision as a change, and a chain of no entries is not a chain.
*
* Replaces whatever chain the antenna already held rather than appending to
* it, so a client always sends the whole list it means.
*
* **The chain does not aim the antenna when it arrives.** It is stored, and
* the first entry is applied on the first evaluation that finds the craft
* without a link. An antenna already carrying traffic keeps carrying it: a
* chain is a fallback, and arming one must not cost the operator the link they
* still have.
*/
export interface RealAntennasTargetChainArgs
{
	/** Which antenna, as `RealAntennasAntennaState.antennaId` gives it. */
	antennaId: string;
	/**
	* The targets, in the order they are to be tried. Empty clears the chain.
	*
	* Every entry is validated against the antenna's tech level before any of them
	* is stored, on the same gate the single-target command applies, so a chain
	* cannot hold an entry the antenna has not earned.
	*/
	steps: RealAntennasTargetStepArgs[];
	/**
	* How long to leave an entry in place before judging it, in seconds of game
	* time. Omitted takes the default the craft applies.
	*
	* It exists because a link is not lost and regained instantly: an aim point
	* takes a moment to be solved, and a craft crossing a terminator flickers. Too
	* short and the chain walks past a target that was about to work; too long and
	* a real outage lasts longer than it had to.
	*/
	settleSeconds?: number;
}
/**
* One antenna's fallback chain as the craft currently holds it, on the
* `realantennas.antennaChains` channel: the list, which entry is in place, and
* why. The channel value is a bare ARRAY of these, one entry per antenna of
* the reported craft that has a chain, so an empty array means the craft has
* none.
*
* DELAYED, for the same reason `realantennas.antennas` is: this is state held
* on the craft, and the walk that changes it happens there.
*
* Scoped to the REPORTED craft, though the craft walks every chain it holds. A
* chain set on another vessel keeps being evaluated and is simply not
* described here, because a delayed channel is delayed by the reported
* vessel's own light-time and cannot carry another craft's state at the right
* age.
*/
export interface RealAntennasAntennaChain
{
	/** Which antenna, as `RealAntennasAntennaState.antennaId` gives it. */
	antennaId: string;
	/** The chain, in the order the craft tries it. */
	steps: RealAntennasTargetStep[];
	/**
	* Which entry the antenna is currently aimed at, as an index into
	* `RealAntennasAntennaChain.steps`.
	*
	* `null` means the walk has not started: the craft has had a link for as long
	* as it has held this chain, so no entry has ever been applied and the antenna
	* is still aimed wherever it was. That is the normal resting state of a
	* fallback, not a fault.
	*/
	activeStep?: Value<"count"> | null;
	/**
	* What the walk is doing: `holding` (the craft has a link, nothing to do),
	* `settling` (an entry was just applied and is being given its time),
	* `walking` (no link, and entries are being tried), or `blocked` (there is no
	* link and the chain cannot act, with `RealAntennasAntennaChain.detail` saying
	* why).
	*/
	state: string;
	/**
	* Why the walk is in the state it is, in one sentence for an operator. Always
	* present for `blocked`, because a chain that cannot act is the one case where
	* the state alone is not enough to act on.
	*/
	detail?: string;
	/** The settle time in force for this chain (seconds of game time). */
	settleSeconds: Value<"s">;
	/**
	* When the craft last aimed this antenna from the chain. `null` while
	* `RealAntennasAntennaChain.activeStep` is null, there being no such moment.
	*/
	lastAppliedUt?: Value<"ut"> | null;
	/**
	* How many times the walk has been all the way through the chain without the
	* craft regaining a link. Zero on a chain that is holding.
	*
	* It is the number that says a chain has stopped being a fallback and become a
	* search: every entry has been tried and none of them worked, and the cause is
	* not in the list.
	*/
	laps: Value<"count">;
	/**
	* Whether the craft holding this antenna has a comms link, which is the signal
	* the whole walk turns on.
	*
	* `null` means nobody could read it, and the walk treats that as a reason NOT
	* to act: advancing on an unreadable signal would slew a dish that may be
	* carrying the link.
	*/
	connected?: boolean | null;
	/**
	* Whether THIS antenna is an endpoint of one of the craft's live links, rather
	* than a dish aimed somewhere that nothing is using.
	*
	* It is not what the walk decides on, and it is what tells an operator whether
	* the entry in place is the one doing the work: a craft can be connected
	* through an omni while the chain's dish points at nothing. `null` when it
	* could not be read.
	*/
	carrying?: boolean | null;
	meta: PayloadMeta;
}
/**
* The `comms.linkQuality` payload: RealAntennas-ONLY (absent without RA). Link
* margin normalised to 0..1 (comms-uplink-design.md §2.2/§4.3).
*/
export interface CommsLinkQuality
{
	value: Value<"ratio">;
	meta: PayloadMeta;
}
/**
* The `comms.dataRate` payload: RealAntennas-ONLY. Bidirectional link data
* rate in bits/sec, read live per-hop off the RA CommNet graph
* (comms-uplink-design.md §4.3: "reachable cleanly").
*/
export interface CommsDataRate
{
	upBitsPerSec: Value<"bit/s">;
	downBitsPerSec: Value<"bit/s">;
	meta: PayloadMeta;
}
/**
* The `comms.linkMargin` payload: RealAntennas-ONLY. Re-derived by the
* RealAntennas uplink from RA's public static link-budget math, NOT read off a
* live field (comms-uplink-design.md §4.3: margin is computed transiently
* inside RA's internal Precompute job and not stored anywhere public).
*/
export interface CommsLinkMargin
{
	decibelMargin: Value<"dB">;
	closesLink: boolean;
	meta: PayloadMeta;
}
/**
* RealAntennas' namespace of a `CommsHop`'s provider extension bag: the
* per-hop RA facts core's shared `CommsHop` shape does not (and should not)
* declare, carried under the provider id `"realantennas"` and typed HERE
* rather than in core (see `Sitrep.Contract/ProviderExtensions.cs` for the
* mechanism, and a sibling Uplink's reliability extension for the exemplar).
*
* It rides `comms.path`, which is already the TrueNow geometry SignalDelay
* consumes, so every field here is TrueNow like the rest of the comms family:
* these are properties of the link KSC is computing right now, several of them
* (data rate) parallel to the delay computation, so delay-gating them would be
* circular.
*
* Every field is nullable: absent under bare CommNet (the vanilla backend
* leaves the whole bag null), and individually absent when a particular RA
* read fails, the same typed-absence posture as the rest of this slice. Read
* client-side through `readRealAntennasHopExt`, never by reaching into
* `hop.extensions?.realantennas` and casting.
*/
export interface RealAntennasHopExt
{
	/** RF band the hop is on (L/S/X/K): `RealAntenna.RFBand.name`. */
	band?: string;
	/** Antenna tech level (0..9): the progression axis behind the rate ceiling. */
	techLevel?: Value<"count"> | null;
	/**
	* Negotiated modulation order: shows the link stepping down under a thin
	* margin.
	*/
	modulationBits?: Value<"count"> | null;
	/** Active FEC encoder name (e.g. "Reed-Solomon 255/223", "Turbo 1/2"). */
	encoder?: string;
	/** Encoder coding rate (0..1): the FEC overhead the rate already includes. */
	codingRate?: Value<"ratio"> | null;
	/** Required Eb/N0 (dB) to close the link at this encoder: RA's own figure. */
	requiredEbN0?: Value<"dB"> | null;
	/** Dish beamwidth (degrees): pointing tightness/sensitivity. */
	beamwidth?: Value<"°"> | null;
	/** Transmit electric-charge draw (units/s): the comms power cost of this hop. */
	powerDrawEc?: Value<"units/s"> | null;
	/**
	* Reverse-direction throughput (bits/sec): the opposite of the forward rate
	* this Uplink publishes on `realantennas.hopRates`, off the same live
	* RACommLink. The backend only surfaced the forward direction before.
	*/
	reverseBitsPerSec?: Value<"bit/s"> | null;
}
/**
* One entry of the `realantennas.hopRates` channel: the RealAntennas forward
* band rate for a single hop, keyed by the SAME node ids `comms.path` already
* carries (`RaCommsBackend.NodeId(link.a)`/ `NodeId(link.b)`), so a client can
* join a rate onto the route the core schedule already renders WITHOUT this
* Uplink republishing the topology.
*
* RealAntennas' relay graph subclasses stock CommNet's (`RACommNode :
* CommNet.CommNode`, `RACommLink : CommNet.CommLink`), so the hop set and its
* node ids are identical to `comms.path`'s: this channel ONLY embellishes each
* existing hop with its bitrate, it never re-derives the path. The channel
* value is a bare ARRAY of these entries (one per hop that has a readable
* rate), self-flattened at the publish boundary by `RaWire.HopRates` the same
* way this Uplink's other channels flatten, so core's serializer never needs
* to know the type exists.
*
* TRUE-NOW like the rest of the comms family: it describes the link AS KSC
* SEES IT, computed ground-side. Absent entirely without RealAntennas
* installed (this Uplink is not even elected), and a hop whose rate cannot be
* read this tick simply yields no entry, never a 0 sentinel.
*/
export interface RealAntennasHopRate
{
	/** The hop's source node id, identical to the matching `CommsHop.From`. */
	fromNodeId: string;
	/** The hop's destination node id, identical to the matching `CommsHop.To`. */
	toNodeId: string;
	/** Forward band rate (bits/sec) for this hop, off the live RACommLink. */
	bitsPerSec: Value<"bit/s">;
}
/**
* One antenna of the reported craft, on the `realantennas.antennas` channel:
* what it is, what it can do, and where it is currently pointed. The channel
* value is a bare ARRAY of these, one entry per antenna, in the order
* RealAntennas holds them.
*
* DELAYED, unlike the rest of this Uplink's channels. The others describe the
* LINK as KSC computes it ground-side and are true now; where a dish is
* pointed is a property of the craft, and the commands that change it ride the
* Courier's light-time delay. A true-now readout beside a delayed command
* would show the new aim point while the command was still in flight.
*/
export interface RealAntennasAntennaState
{
	/**
	* The address both targeting commands take, stable across a reordering of the
	* craft's antenna list: the flight id of the part the antenna belongs to, plus
	* an ordinal when one part carries several antennas (`"1234567890/0"`). Falls
	* back to `"index/<n>"` for an antenna whose part cannot be read, which is the
	* unloaded case.
	*
	* An index alone would not do. Both commands are `Delayed`, so a command
	* dispatched against "the second antenna" arrives minutes later against
	* whatever is second BY THEN, and a decoupled part between the two moments
	* aims a different dish.
	*/
	antennaId: string;
	/**
	* Position in RealAntennas' own antenna list for this craft: display order,
	* not an address.
	*/
	index: Value<"count">;
	/** The antenna's name, which is the part title. */
	name?: string;
	/**
	* Whether this antenna can hold a target at all. RealAntennas derives it from
	* gain alone (a dish is an antenna with more than 5 dBi; there is no stored
	* "steerable" flag), and an antenna that is not steerable refuses both
	* commands.
	*
	* `null` means the antenna is here and nobody could read its shape: NOT that
	* it is an omni. Collapsing the two badges a dish as an omni and hides its
	* targeting controls on the strength of a read that never happened. Both
	* commands refuse an unreadable antenna as well, but they say which of the two
	* refusals it is.
	*/
	steerable?: boolean | null;
	/**
	* Whether this antenna currently holds a target. The fields below describe it
	* when true and are all null when false.
	*
	* False on a steerable antenna means it has not been aimed yet, which is the
	* state a dish leaves the editor in. There is no command that returns one to
	* it: both targeting commands move an antenna between targets, and
	* RealAntennas itself never puts a vessel dish back.
	*
	* `null` means nobody could read whether it holds one, which is a third answer
	* and not a quieter "no". The target fields below are all null in that case
	* too, for want of a target to describe rather than because there is none.
	*/
	targeted?: boolean | null;
	/** Antenna gain (dBi), the quantity beamwidth and steerability both come off. */
	gain?: Value<"dB"> | null;
	/** Antenna tech level (0..9): the level the mode gate compares against. */
	techLevel?: Value<"count"> | null;
	/**
	* Beamwidth (degrees), from gain. RealAntennas draws the 3 dB cone at half
	* this and the 10 dB cone at all of it, so this is the wider of the two.
	*/
	beamwidth?: Value<"°"> | null;
	/** The 3 dB cone half-angle (degrees): half the beamwidth. */
	cone3Db?: Value<"°"> | null;
	/** The 10 dB cone half-angle (degrees): the beamwidth itself. */
	cone10Db?: Value<"°"> | null;
	/**
	* The near-field limit a tight beam imposes (metres): RealAntennas reports
	* zero for an antenna holding no target, and for a beam 90° or wider.
	*/
	minimumDistance?: Value<"m"> | null;
	/**
	* The STORED kind of the current target: `Vessel`, `BodyLatLonAlt`, `AzEl` or
	* `OrbitRelative`. Null when the antenna holds no target.
	*
	* `BodyCenter` never appears here, and the omission is deliberate.
	* RealAntennas has five mode NAMES and four target classes: "body centre" is a
	* way of filling in a `BodyLatLonAlt` (lat 0, lon 0, altitude minus the body's
	* radius) and nothing records that it was chosen that way. Reporting the
	* stored kind is a read; reporting `BodyCenter` would be a guess about how the
	* numbers were arrived at.
	*/
	targetKind?: string;
	/**
	* The target as RealAntennas itself renders it, which is the same string its
	* in-game "Antenna Target" field shows. Null when the antenna holds no target.
	*/
	targetLabel?: string;
	/**
	* The target vessel's id, for a `Vessel` target. For `AzEl` and
	* `OrbitRelative` this is the craft the angles are measured FROM, which is the
	* antenna's own, not something being aimed at.
	*/
	targetVesselId?: string;
	/** The body a `BodyLatLonAlt` target is on. */
	targetBodyName?: string;
	/** Latitude of a `BodyLatLonAlt` target (degrees). */
	targetLatitude?: Value<"°"> | null;
	/** Longitude of a `BodyLatLonAlt` target (degrees). */
	targetLongitude?: Value<"°"> | null;
	/**
	* Altitude of a `BodyLatLonAlt` target (metres above the surface). A value of
	* minus the body's radius is the body's centre, which is what RealAntennas
	* writes for its own "Body Center" affordance and for the default target it
	* gives an untargeted dish.
	*/
	targetAltitude?: Value<"m"> | null;
	/** Azimuth of an `AzEl` target (degrees, 0..360). */
	targetAzimuth?: Value<"°"> | null;
	/** Elevation of an `AzEl` or `OrbitRelative` target (degrees, -90..90). */
	targetElevation?: Value<"°"> | null;
	/** Deflection from prograde of an `OrbitRelative` target (degrees, -180..180). */
	targetForward?: Value<"°"> | null;
	/**
	* The mode names `realantennas.antenna.target` will accept for THIS antenna:
	* every mode the install declares whose tech level this antenna has reached.
	*
	* It is per-antenna because the gate is per-antenna, and it is on the wire
	* because the gate is DATA. The five levels are config, not code, and Realism
	* Overhaul moves three of them, so a client that hard-coded the stock numbers
	* would offer modes this install refuses and hide modes it allows.
	*/
	availableTargetModes: string[];
	meta: PayloadMeta;
}
/**
* Args for `realantennas.antenna.target`: point one antenna at one thing.
*
* Which of the optional fields are read depends on
* `RealAntennasTargetArgs.mode`, and a field the mode does not read is ignored
* rather than refused.
*/
export interface RealAntennasTargetArgs
{
	/** Which antenna, as `RealAntennasAntennaState.antennaId` gives it. */
	antennaId: string;
	/**
	* One of `Vessel`, `BodyCenter`, `BodyLatLonAlt`, `AzEl`, `OrbitRelative`.
	* Anything else is refused.
	*
	* `BodyCenter` is accepted here even though nothing stores it (see
	* `RealAntennasAntennaState.targetKind`): it is the mode the tech-level gate
	* is declared against, and it saves every caller having to know that the
	* body's centre is written as latitude 0, longitude 0, altitude minus the
	* radius. It is stored as, and reads back as, `BodyLatLonAlt`.
	*/
	mode: string;
	/**
	* The vessel to point at, for `Vessel`. Ignored by every other mode: `AzEl`
	* and `OrbitRelative` are measured from the antenna's OWN craft, which the
	* handler fills in, so a caller cannot aim one craft's dish by another craft's
	* attitude.
	*/
	vesselId?: string;
	/** The body, for `BodyCenter` and `BodyLatLonAlt`. Empty means the home body. */
	bodyName?: string;
	/** Latitude (degrees, -90..90), for `BodyLatLonAlt`. */
	latitude?: number;
	/** Longitude (degrees, -180..360), for `BodyLatLonAlt`. */
	longitude?: number;
	/**
	* Altitude above the surface (metres), for `BodyLatLonAlt`. Omitted means the
	* surface, altitude 0: the aim point is a three-component vector with no
	* spelling for a missing component, and a lat/lon with no altitude is not an
	* ambiguous request. `RealAntennasTargetArgs.latitude` and
	* `RealAntennasTargetArgs.longitude` have no such default and are REFUSED when
	* absent, because 0, 0 is a specific place nobody asked for.
	*/
	altitude?: number;
	/** Azimuth (degrees, 0..360), for `AzEl`. */
	azimuth?: number;
	/** Elevation (degrees, -90..90), for `AzEl` and `OrbitRelative`. */
	elevation?: number;
	/** Deflection from prograde (degrees, -180..180), for `OrbitRelative`. */
	forward?: number;
}
/** Args for `realantennas.antenna.targetHome`: one antenna, no options. */
export interface RealAntennasAntennaArgs
{
	/** Which antenna, as `RealAntennasAntennaState.antennaId` gives it. */
	antennaId: string;
}
