//     This code was generated by the Sitrep contract error-code codegen
//     (Sitrep.Contract.RtConfig.EmitErrorCodeMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type { ErrorCodeDeclaration } from "@ksp-gonogo/sitrep-sdk";

/**
 * The refusals RP-1's commands answer with that say more than a core code can:
 * each refines the root a client classifies it by.
 *
 * @category Error codes
 */
export const Rp1ErrorCodes = {
  /**
   * RP-1 is installed but is not managing this save, so none of its career
   * commands apply to it. A property of the save rather than of the moment.
   */
  NotManaging: "rp1.notManaging",
  /**
   * RP-1's space centre, which holds every queue and complex these commands act
   * on, is not loaded in the current scene.
   */
  SpaceCentreNotLoaded: "rp1.spaceCentreNotLoaded",
  /**
   * The installed RP-1 build lacks a member this Uplink reads or calls, so the
   * command could not be carried out. The detail names which one.
   */
  BuildUnrecognised: "rp1.buildUnrecognised",
} as const;
export type Rp1ErrorCodes = (typeof Rp1ErrorCodes)[keyof typeof Rp1ErrorCodes];

/**
 * Every code declared here, with the sentence an operator reads for it.
 *
 * @category Error codes
 */
export const RP1_ERROR_CODES: readonly ErrorCodeDeclaration[] = [
  {
    id: "rp1.notManaging",
    kind: "refusal",
    refines: "careerModeRequired",
    origin: null,
    sentence: "RP-1 is not managing this save",
    meaning: "RP-1 is installed but is not managing this save, so none of its career commands apply to it. A property of the save rather than of the moment.",
  },
  {
    id: "rp1.spaceCentreNotLoaded",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "RP-1's space centre is not loaded",
    meaning: "RP-1's space centre, which holds every queue and complex these commands act on, is not loaded in the current scene.",
  },
  {
    id: "rp1.buildUnrecognised",
    kind: "refusal",
    refines: "unreadable",
    origin: null,
    sentence: "this RP-1 build is not one this Uplink recognises",
    meaning: "The installed RP-1 build lacks a member this Uplink reads or calls, so the command could not be carried out. The detail names which one.",
  },
];
