//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.
//
// THIS IS NOT A LIST OF EVERY TOPIC ON THE WIRE, and it cannot become one.
// A DYNAMIC namespace is registered at RUNTIME through
// `IUplinkHost.RegisterDynamicNamespace` and materialises its topics per
// subject, so no [SitrepTopic]-tagged type exists for reflection to find and
// nothing about it appears below: `silence.<guid>.*`,
// `currency.<guid>.<currency>`, `vessel.partActions.<flightId>`, and each
// Uplink's own. Asking this file "is there per-vessel X" gets a confident no
// for a topic that has been published all along: `fleet.<guid>.orbit` was
// surveyed as missing that way. To enumerate the dynamic half, grep the mod
// for `RegisterDynamicNamespace` instead.
//
// THE PREFIX IS NOT THE TEST, and `fleet.` is the case that proves it.
// `fleet.silence` is statically declared and IS below; `fleet.<guid>.<field>`
// is dynamic and is not. An earlier version of this header listed `fleet.`
// among the namespaces nothing of which appears here, which the very map it
// introduces contradicts. Reading either half as evidence about the other
// goes wrong in both directions.

import type {
  Rp1Avionics,
  Rp1BuildCost,
  Rp1BuildItemEntry,
  Rp1BuildableCraftEntry,
  Rp1CareerEvents,
  Rp1CentreEntry,
  Rp1ComplexEntry,
  Rp1Confidence,
  Rp1ConstructionEntry,
  Rp1CrewEntry,
  Rp1CrewProgram,
  Rp1FacilityEntry,
  Rp1FundTarget,
  Rp1FundingCurveEntry,
  Rp1LcPricing,
  Rp1OperationEntry,
  Rp1PadEntry,
  Rp1Personnel,
  Rp1ProgramEntry,
  Rp1ProgramSlots,
  Rp1ResearchEntry,
  Rp1RushTerms,
  Rp1Tooling,
  Rp1TrainingCourseEntry,
  Rp1TrainingTemplateEntry,
  Rp1WarehouseItemEntry,
} from "./contract.js";

export interface GeneratedTopicPayloadMap {
  "rp1.avionics": Rp1Avionics;
  "rp1.buildCost": Rp1BuildCost;
  "rp1.buildQueue": Rp1BuildItemEntry[];
  "rp1.buildable": Rp1BuildableCraftEntry[];
  "rp1.careerEvents": Rp1CareerEvents;
  "rp1.centres": Rp1CentreEntry[];
  "rp1.complexes": Rp1ComplexEntry[];
  "rp1.confidence": Rp1Confidence;
  "rp1.constructions": Rp1ConstructionEntry[];
  "rp1.crew": Rp1CrewEntry[];
  "rp1.crewProgram": Rp1CrewProgram;
  "rp1.facilities": Rp1FacilityEntry[];
  "rp1.fundTarget": Rp1FundTarget;
  "rp1.lcPricing": Rp1LcPricing;
  "rp1.operations": Rp1OperationEntry[];
  "rp1.pads": Rp1PadEntry[];
  "rp1.personnel": Rp1Personnel;
  "rp1.programFundingCurves": Rp1FundingCurveEntry[];
  "rp1.programSlots": Rp1ProgramSlots;
  "rp1.programs": Rp1ProgramEntry[];
  "rp1.research": Rp1ResearchEntry[];
  "rp1.rushTerms": Rp1RushTerms;
  "rp1.tooling": Rp1Tooling;
  "rp1.training": Rp1TrainingCourseEntry[];
  "rp1.trainingCatalogue": Rp1TrainingTemplateEntry[];
  "rp1.warehouse": Rp1WarehouseItemEntry[];
}

export const GENERATED_TOPIC_IDS = [
  "rp1.avionics",
  "rp1.buildCost",
  "rp1.buildQueue",
  "rp1.buildable",
  "rp1.careerEvents",
  "rp1.centres",
  "rp1.complexes",
  "rp1.confidence",
  "rp1.constructions",
  "rp1.crew",
  "rp1.crewProgram",
  "rp1.facilities",
  "rp1.fundTarget",
  "rp1.lcPricing",
  "rp1.operations",
  "rp1.pads",
  "rp1.personnel",
  "rp1.programFundingCurves",
  "rp1.programSlots",
  "rp1.programs",
  "rp1.research",
  "rp1.rushTerms",
  "rp1.tooling",
  "rp1.training",
  "rp1.trainingCatalogue",
  "rp1.warehouse",
] as const;
