//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/** Every token first-party payloads use (Sitrep.Contract.Units). */
export type KnownSitrepUnit =
  | "%"
  | "1"
  | "K"
  | "Mit"
  | "W/m²"
  | "bit"
  | "bit/s"
  | "bp"
  | "bp/s"
  | "confidence"
  | "count"
  | "dB"
  | "enum"
  | "f/day"
  | "flag"
  | "funds"
  | "g"
  | "h"
  | "id"
  | "isp"
  | "kN"
  | "kPa"
  | "kW"
  | "kg"
  | "kg/m³"
  | "kg/s"
  | "km"
  | "m"
  | "m/s"
  | "m²"
  | "m³"
  | "m³/s²"
  | "n/a"
  | "rad"
  | "rad/s"
  | "ratio"
  | "rep"
  | "rep/day"
  | "rpm"
  | "s"
  | "science"
  | "science/day"
  | "t"
  | "text"
  | "units"
  | "units/s"
  | "ut"
  | "°"
;

/**
 * A declared unit. OPEN on purpose.
 *
 * The known tokens above still autocomplete, and a typo in first-party
 * code is still caught at codegen time by the catalog check. The open arm
 * exists because a third-party Uplink CANNOT add to Sitrep.Contract.Units:
 * it is a const-string class compiled into the contract assembly. Closing
 * this union would therefore have meant an Uplink could never declare a
 * unit at all, which contradicts third parties being first-class.
 *
 * A consumer teaches the client what an unknown symbol MEANS by declaring it
 * in UnitDeclarations and calling registerUnit from @ksp-gonogo/sitrep-sdk.
 * Until it does, the value still renders, bare and unscaled.
 */
export type SitrepUnit = KnownSitrepUnit | (string & {});

/** Declared units for one payload shape, keyed by camelCased field name. */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "Rp1Avionics": {
    limitedByNonInterplanetary: "flag",
    lockLevel: "enum",
    supportedMassTons: "t",
    vesselMassTons: "t",
  },
  "Rp1BuildCost": {
    rolloutCost: "funds",
    toolingCost: "funds",
    unlockCost: "funds",
    untooledSurcharge: "funds",
    vehicleCost: "funds",
  },
  "Rp1BuildItemEntry": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    progress: "bp",
    progressRatio: "ratio",
    projectType: "enum",
    rate: "bp/s",
    shipId: "id",
    shipName: "text",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
  },
  "Rp1BuildRepeatArgs": {
    id: "id",
  },
  "Rp1BuildStartArgs": {
    craftFile: "id",
    facility: "enum",
    lcId: "id",
  },
  "Rp1BuildableComplex": {
    eligible: "flag",
    kscDisplayName: "text",
    kscName: "id",
    lcId: "id",
    name: "text",
    refusals: "text",
  },
  "Rp1BuildableCraftEntry": {
    cost: "funds",
    craftFile: "id",
    facility: "enum",
    lockedParts: "text",
    mass: "t",
    missingParts: "text",
    partCount: "count",
    shipName: "text",
    unpurchasedParts: "text",
  },
  "Rp1CareerEventEntry": {
    builtAt: "enum",
    cost: "funds",
    detail: "enum",
    isAdd: "flag",
    kind: "enum",
    launchId: "id",
    name: "text",
    repChange: "rep",
    ut: "ut",
  },
  "Rp1CareerEvents": {
    enabled: "flag",
  },
  "Rp1CentreEntry": {
    anyOperational: "flag",
    engineers: "count",
    groundStation: "id",
    idleSalaryPerDay: "f/day",
    isActive: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchComplexCount: "count",
    salaryPerDay: "f/day",
    unassignedEngineers: "count",
    upkeepPerDay: "f/day",
  },
  "Rp1ComplexDismantleArgs": {
    lcId: "id",
  },
  "Rp1ComplexEntry": {
    canIntegrate: "flag",
    efficiency: "ratio",
    efficiencyGroupKey: "id",
    efficiencySharedWith: "id",
    engineers: "count",
    humanRated: "flag",
    isOperational: "flag",
    isRushing: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchPadCount: "count",
    lcId: "id",
    lcType: "enum",
    massMax: "t",
    massMin: "t",
    massOrig: "t",
    maxEngineers: "count",
    name: "text",
    newPadCost: "funds",
    rate: "bp/s",
    resourcesHandled: "id",
    rushSalaryDeltaPerDay: "f/day",
    salaryPerDay: "f/day",
    sizeMaxDepth: "m",
    sizeMaxHeight: "m",
    sizeMaxWidth: "m",
    upkeepPerDay: "f/day",
  },
  "Rp1ComplexModifyArgs": {
    assignEngineersOnComplete: "flag",
    humanRated: "flag",
    lcId: "id",
    massMax: "t",
  },
  "Rp1ComplexNewArgs": {
    assignEngineersOnComplete: "flag",
    humanRated: "flag",
    kscName: "id",
    massMax: "t",
    name: "id",
  },
  "Rp1ComplexRenameArgs": {
    lcId: "id",
    name: "id",
  },
  "Rp1ComplexRushArgs": {
    lcId: "id",
    rushing: "flag",
  },
  "Rp1ComplexSizeArgs": {
    sizeMaxDepth: "m",
    sizeMaxHeight: "m",
    sizeMaxWidth: "m",
  },
  "Rp1Confidence": {
    confidence: "confidence",
    earned: "confidence",
  },
  "Rp1ConstructionEntry": {
    cost: "funds",
    currentLevel: "count",
    engineersToReadd: "count",
    facilityType: "enum",
    isModify: "flag",
    kind: "enum",
    kscName: "id",
    lcId: "id",
    name: "text",
    padId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    spentCost: "funds",
    spentRushCost: "funds",
    stalled: "flag",
    targetLevel: "count",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    workRate: "ratio",
  },
  "Rp1ContractPayloadArgs": {
    commsPayload: "kg",
    weatherPayload: "kg",
  },
  "Rp1CrewEntry": {
    latestRetiresAtUt: "ut",
    name: "id",
    nextTrainingExpiryTarget: "text",
    nextTrainingExpiryUt: "ut",
    retired: "flag",
    retirementExtensionUsedSeconds: "s",
    retiresAtUt: "ut",
    trainingCourse: "text",
    trainingExpiryCount: "count",
    trainingFinishesAtUt: "ut",
    trainingFractionComplete: "ratio",
    trainingStarted: "flag",
    trainingTarget: "text",
    trainingType: "text",
  },
  "Rp1CrewProgram": {
    courses: "count",
    coursesStarted: "count",
    crewInTraining: "count",
    crewRnREnabled: "flag",
    missionTrainingEnabled: "flag",
    missionTrainingRate: "1",
    proficiencyTrainingRate: "1",
    retirementEnabled: "flag",
    retirementExtensionCapSeconds: "s",
  },
  "Rp1FacilityEntry": {
    currentTier: "count",
    facility: "enum",
    maxTier: "count",
    upgradeCost: "funds",
    upgradedByRp1: "flag",
  },
  "Rp1FacilityUpgradeArgs": {
    facility: "id",
  },
  "Rp1FundTarget": {
    active: "flag",
    originalFunds: "funds",
    targetFunds: "funds",
    timeLeft: "s",
  },
  "Rp1FundingCurveEntry": {
    isDefault: "flag",
    name: "id",
  },
  "Rp1FundingCurveKey": {
    frac: "ratio",
    inTangent: "1",
    outTangent: "1",
    paidFraction: "ratio",
  },
  "Rp1HireTarget": {
    active: "flag",
    currentCount: "count",
    isResearch: "flag",
    lcId: "id",
    leftToHire: "count",
    targetCount: "count",
    timeLeft: "s",
  },
  "Rp1HireTargetSetArgs": {
    lcId: "id",
    reserveFunds: "funds",
    targetCount: "count",
  },
  "Rp1LcPricing": {
    additionalPadCostMult: "ratio",
  },
  "Rp1LcResourcePrice": {
    name: "id",
    padCostPerUnit: "funds",
  },
  "Rp1LeaderEntry": {
    canRemoveFromUt: "ut",
    deactivateReputation: "rep",
    freeToRemoveFromUt: "ut",
    reactivateCooldown: "s",
    removeOnDeactivate: "flag",
    setupConfidence: "confidence",
    setupFunds: "funds",
    setupReputation: "rep",
    setupScience: "science",
    strategyId: "id",
  },
  "Rp1OperationEntry": {
    associatedVesselId: "id",
    blockingPeers: "count",
    cost: "funds",
    costRemaining: "funds",
    kscName: "id",
    launchPadId: "id",
    lcId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    type: "enum",
  },
  "Rp1PadDismantleArgs": {
    lcId: "id",
    padId: "id",
  },
  "Rp1PadEntry": {
    fractionalLevel: "ratio",
    hasVesselWaiting: "flag",
    isOperational: "flag",
    kscName: "id",
    launchSiteName: "id",
    lcId: "id",
    level: "count",
    name: "text",
    padId: "id",
    status: "enum",
    waitingVesselName: "text",
  },
  "Rp1PadNewArgs": {
    lcId: "id",
    name: "id",
  },
  "Rp1PadRenameArgs": {
    lcId: "id",
    name: "id",
    padId: "id",
  },
  "Rp1Personnel": {
    applicants: "count",
    engineerSalaryPerDay: "f/day",
    engineerSalaryPerYear: "funds",
    idleSalaryMult: "ratio",
    researcherSalaryPerDay: "f/day",
    researcherSalaryPerYear: "funds",
    researchers: "count",
    totalEngineers: "count",
  },
  "Rp1PersonnelAssignArgs": {
    engineers: "count",
    lcId: "id",
  },
  "Rp1ProgramEntry": {
    acceptedUt: "ut",
    canAccept: "flag",
    canComplete: "flag",
    completedUt: "ut",
    confidenceCost: "confidence",
    deadlineUt: "ut",
    durationSeconds: "s",
    fracElapsed: "ratio",
    fundingCurve: "text",
    fundsPaidOut: "funds",
    fundsRemaining: "funds",
    isHumanSpaceflight: "flag",
    lastPaymentUt: "ut",
    name: "id",
    nominalDurationSeconds: "s",
    objectivesCompletedUt: "ut",
    objectivesMet: "flag",
    objectivesText: "text",
    programsToDisableOnAccept: "id",
    repDeltaOnCompletePerYearEarly: "rep",
    repPenaltyAssessed: "rep",
    repPenaltyPerYearLate: "rep",
    requirementsMet: "flag",
    requirementsText: "text",
    slots: "count",
    speed: "enum",
    status: "enum",
    title: "text",
    totalFunding: "funds",
  },
  "Rp1ProgramPaymentEntry": {
    cumulativeFunds: "funds",
    funds: "funds",
    year: "count",
  },
  "Rp1ProgramSlots": {
    activeCount: "count",
    completedCount: "count",
    freeSlots: "count",
    maxSlots: "count",
    usedSlots: "count",
  },
  "Rp1ProgramSpeedOption": {
    confidenceCost: "confidence",
    durationSeconds: "s",
    speed: "enum",
  },
  "Rp1RequiredTechEntry": {
    id: "id",
    parts: "text",
    title: "text",
  },
  "Rp1ResearchEntry": {
    endYear: "count",
    progress: "count",
    progressRatio: "ratio",
    rate: "count",
    scienceCost: "count",
    stalled: "flag",
    startYear: "count",
    techId: "id",
    techName: "text",
    timeLeftSeconds: "s",
    workRate: "ratio",
  },
  "Rp1RolloutArgs": {
    id: "id",
    pad: "id",
  },
  "Rp1RushTerms": {
    rateMult: "ratio",
    salaryMult: "ratio",
  },
  "Rp1StrategyActivateArgs": {
    factor: "ratio",
    strategyId: "id",
  },
  "Rp1TechResearchArgs": {
    techId: "id",
  },
  "Rp1Tooling": {
    toolAllCost: "funds",
    untooledCount: "count",
  },
  "Rp1ToolingEntry": {
    parameterSummary: "text",
    partId: "id",
    partTitle: "text",
    refittable: "flag",
    symmetryCounterparts: "count",
    tooled: "flag",
    toolingCost: "funds",
    toolingType: "id",
    toolingTypeTitle: "text",
    untooledSurcharge: "funds",
  },
  "Rp1ToolingRefitArgs": {
    diameter: "m",
    length: "m",
    partId: "id",
    rfType: "id",
  },
  "Rp1ToolingRefitTarget": {
    diameter: "m",
    length: "m",
    rfType: "id",
  },
  "Rp1TrainingCourseEntry": {
    completed: "flag",
    completesAtUt: "ut",
    description: "text",
    id: "id",
    isTemporary: "flag",
    name: "text",
    seatMax: "count",
    seatMin: "count",
    started: "flag",
    students: "id",
    studentsAvailableAtUt: "ut",
    target: "id",
    type: "enum",
  },
  "Rp1TrainingEnrolArgs": {
    crew: "id",
    templateId: "id",
  },
  "Rp1TrainingLeaveArgs": {
    crewName: "id",
  },
  "Rp1TrainingTemplateEntry": {
    baseTime: "s",
    description: "text",
    id: "id",
    isTemporary: "flag",
    name: "text",
    seatMax: "count",
    seatMin: "count",
    target: "id",
    type: "enum",
    unlocked: "flag",
  },
  "Rp1VehicleArgs": {
    id: "id",
  },
  "Rp1WarehouseItemEntry": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    projectType: "enum",
    rolloutCost: "funds",
    rolloutRefusals: "text",
    shipId: "id",
    shipName: "text",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "rp1.avionics": {
    limitedByNonInterplanetary: "flag",
    lockLevel: "enum",
    supportedMassTons: "t",
    vesselMassTons: "t",
  },
  "rp1.buildCost": {
    rolloutCost: "funds",
    toolingCost: "funds",
    unlockCost: "funds",
    untooledSurcharge: "funds",
    vehicleCost: "funds",
  },
  "rp1.buildQueue": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    progress: "bp",
    progressRatio: "ratio",
    projectType: "enum",
    rate: "bp/s",
    shipId: "id",
    shipName: "text",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
  },
  "rp1.buildable": {
    cost: "funds",
    craftFile: "id",
    facility: "enum",
    lockedParts: "text",
    mass: "t",
    missingParts: "text",
    partCount: "count",
    shipName: "text",
    unpurchasedParts: "text",
  },
  "rp1.careerEvents": {
    enabled: "flag",
  },
  "rp1.centres": {
    anyOperational: "flag",
    engineers: "count",
    groundStation: "id",
    idleSalaryPerDay: "f/day",
    isActive: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchComplexCount: "count",
    salaryPerDay: "f/day",
    unassignedEngineers: "count",
    upkeepPerDay: "f/day",
  },
  "rp1.complexes": {
    canIntegrate: "flag",
    efficiency: "ratio",
    efficiencyGroupKey: "id",
    efficiencySharedWith: "id",
    engineers: "count",
    humanRated: "flag",
    isOperational: "flag",
    isRushing: "flag",
    kscDisplayName: "text",
    kscName: "id",
    launchPadCount: "count",
    lcId: "id",
    lcType: "enum",
    massMax: "t",
    massMin: "t",
    massOrig: "t",
    maxEngineers: "count",
    name: "text",
    newPadCost: "funds",
    rate: "bp/s",
    resourcesHandled: "id",
    rushSalaryDeltaPerDay: "f/day",
    salaryPerDay: "f/day",
    sizeMaxDepth: "m",
    sizeMaxHeight: "m",
    sizeMaxWidth: "m",
    upkeepPerDay: "f/day",
  },
  "rp1.confidence": {
    confidence: "confidence",
    earned: "confidence",
  },
  "rp1.constructions": {
    cost: "funds",
    currentLevel: "count",
    engineersToReadd: "count",
    facilityType: "enum",
    isModify: "flag",
    kind: "enum",
    kscName: "id",
    lcId: "id",
    name: "text",
    padId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    spentCost: "funds",
    spentRushCost: "funds",
    stalled: "flag",
    targetLevel: "count",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    workRate: "ratio",
  },
  "rp1.crew": {
    latestRetiresAtUt: "ut",
    name: "id",
    nextTrainingExpiryTarget: "text",
    nextTrainingExpiryUt: "ut",
    retired: "flag",
    retirementExtensionUsedSeconds: "s",
    retiresAtUt: "ut",
    trainingCourse: "text",
    trainingExpiryCount: "count",
    trainingFinishesAtUt: "ut",
    trainingFractionComplete: "ratio",
    trainingStarted: "flag",
    trainingTarget: "text",
    trainingType: "text",
  },
  "rp1.crewProgram": {
    courses: "count",
    coursesStarted: "count",
    crewInTraining: "count",
    crewRnREnabled: "flag",
    missionTrainingEnabled: "flag",
    missionTrainingRate: "1",
    proficiencyTrainingRate: "1",
    retirementEnabled: "flag",
    retirementExtensionCapSeconds: "s",
  },
  "rp1.facilities": {
    currentTier: "count",
    facility: "enum",
    maxTier: "count",
    upgradeCost: "funds",
    upgradedByRp1: "flag",
  },
  "rp1.fundTarget": {
    active: "flag",
    originalFunds: "funds",
    targetFunds: "funds",
    timeLeft: "s",
  },
  "rp1.lcPricing": {
    additionalPadCostMult: "ratio",
  },
  "rp1.operations": {
    associatedVesselId: "id",
    blockingPeers: "count",
    cost: "funds",
    costRemaining: "funds",
    kscName: "id",
    launchPadId: "id",
    lcId: "id",
    progress: "bp",
    progressRatio: "ratio",
    rate: "bp/s",
    stalled: "flag",
    timeLeftSeconds: "s",
    totalPoints: "bp",
    type: "enum",
  },
  "rp1.pads": {
    fractionalLevel: "ratio",
    hasVesselWaiting: "flag",
    isOperational: "flag",
    kscName: "id",
    launchSiteName: "id",
    lcId: "id",
    level: "count",
    name: "text",
    padId: "id",
    status: "enum",
    waitingVesselName: "text",
  },
  "rp1.personnel": {
    applicants: "count",
    engineerSalaryPerDay: "f/day",
    engineerSalaryPerYear: "funds",
    idleSalaryMult: "ratio",
    researcherSalaryPerDay: "f/day",
    researcherSalaryPerYear: "funds",
    researchers: "count",
    totalEngineers: "count",
  },
  "rp1.programFundingCurves": {
    isDefault: "flag",
    name: "id",
  },
  "rp1.programSlots": {
    activeCount: "count",
    completedCount: "count",
    freeSlots: "count",
    maxSlots: "count",
    usedSlots: "count",
  },
  "rp1.programs": {
    acceptedUt: "ut",
    canAccept: "flag",
    canComplete: "flag",
    completedUt: "ut",
    confidenceCost: "confidence",
    deadlineUt: "ut",
    durationSeconds: "s",
    fracElapsed: "ratio",
    fundingCurve: "text",
    fundsPaidOut: "funds",
    fundsRemaining: "funds",
    isHumanSpaceflight: "flag",
    lastPaymentUt: "ut",
    name: "id",
    nominalDurationSeconds: "s",
    objectivesCompletedUt: "ut",
    objectivesMet: "flag",
    objectivesText: "text",
    programsToDisableOnAccept: "id",
    repDeltaOnCompletePerYearEarly: "rep",
    repPenaltyAssessed: "rep",
    repPenaltyPerYearLate: "rep",
    requirementsMet: "flag",
    requirementsText: "text",
    slots: "count",
    speed: "enum",
    status: "enum",
    title: "text",
    totalFunding: "funds",
  },
  "rp1.research": {
    endYear: "count",
    progress: "count",
    progressRatio: "ratio",
    rate: "count",
    scienceCost: "count",
    stalled: "flag",
    startYear: "count",
    techId: "id",
    techName: "text",
    timeLeftSeconds: "s",
    workRate: "ratio",
  },
  "rp1.rushTerms": {
    rateMult: "ratio",
    salaryMult: "ratio",
  },
  "rp1.tooling": {
    toolAllCost: "funds",
    untooledCount: "count",
  },
  "rp1.training": {
    completed: "flag",
    completesAtUt: "ut",
    description: "text",
    id: "id",
    isTemporary: "flag",
    name: "text",
    seatMax: "count",
    seatMin: "count",
    started: "flag",
    students: "id",
    studentsAvailableAtUt: "ut",
    target: "id",
    type: "enum",
  },
  "rp1.trainingCatalogue": {
    baseTime: "s",
    description: "text",
    id: "id",
    isTemporary: "flag",
    name: "text",
    seatMax: "count",
    seatMin: "count",
    target: "id",
    type: "enum",
    unlocked: "flag",
  },
  "rp1.warehouse": {
    cost: "funds",
    humanRated: "flag",
    id: "id",
    kscName: "id",
    launchSite: "id",
    lcId: "id",
    mass: "t",
    projectType: "enum",
    rolloutCost: "funds",
    rolloutRefusals: "text",
    shipId: "id",
    shipName: "text",
  },
};

/** The nested payload shape each complex field holds, by its interface name. */
export type ShapesByField = Readonly<Record<string, string>>;

/**
 * Which fields hold ANOTHER payload shape, and which one.
 *
 * The unit maps above are flat: they describe one shape's own fields and
 * stop there. That was enough while a unit was only ever looked up, and
 * wrong once the runtime started WRAPPING decoded payloads, because a
 * nested shape's declared units were unreachable from the parent's entry.
 * `vessel.target.orbit.sma` is the plain case: the contract types it as
 * Value<"m">, and without this it arrived as a bare number.
 *
 * An entry names the ELEMENT type and says how many of it the field holds:
 * a bare name is one, a leading `*` a string-keyed DICTIONARY of them, and
 * a trailing `[]` a LIST of them. The element is what a consumer indexes
 * into either way, which is the same convention the topic unit map follows
 * for an array Topic.
 *
 * The plural markers are what separate a path something can SAMPLE from a
 * path that only names a field of an element. `contracts.active.agent` is
 * the second kind: `career.status.contracts.active` is an array, so no
 * sample reaches an `agent` under it.
 */
export const GENERATED_TYPE_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "Rp1BuildCost": {
    requiredTechs: "Rp1RequiredTechEntry[]",
  },
  "Rp1BuildableCraftEntry": {
    complexes: "Rp1BuildableComplex[]",
  },
  "Rp1CareerEvents": {
    events: "Rp1CareerEventEntry[]",
  },
  "Rp1ComplexModifyArgs": {
    size: "Rp1ComplexSizeArgs",
  },
  "Rp1ComplexNewArgs": {
    size: "Rp1ComplexSizeArgs",
  },
  "Rp1FundingCurveEntry": {
    keys: "Rp1FundingCurveKey[]",
  },
  "Rp1LcPricing": {
    resources: "Rp1LcResourcePrice[]",
  },
  "Rp1Personnel": {
    hireTarget: "Rp1HireTarget",
  },
  "Rp1ProgramEntry": {
    fundingPayments: "Rp1ProgramPaymentEntry[]",
    speedOptions: "Rp1ProgramSpeedOption[]",
  },
  "Rp1Tooling": {
    parts: "Rp1ToolingEntry[]",
  },
  "Rp1ToolingEntry": {
    refitTargets: "Rp1ToolingRefitTarget[]",
  },
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "rp1.buildCost": {
    requiredTechs: "Rp1RequiredTechEntry[]",
  },
  "rp1.buildable": {
    complexes: "Rp1BuildableComplex[]",
  },
  "rp1.careerEvents": {
    events: "Rp1CareerEventEntry[]",
  },
  "rp1.lcPricing": {
    resources: "Rp1LcResourcePrice[]",
  },
  "rp1.personnel": {
    hireTarget: "Rp1HireTarget",
  },
  "rp1.programFundingCurves": {
    keys: "Rp1FundingCurveKey[]",
  },
  "rp1.programs": {
    fundingPayments: "Rp1ProgramPaymentEntry[]",
    speedOptions: "Rp1ProgramSpeedOption[]",
  },
  "rp1.tooling": {
    parts: "Rp1ToolingEntry[]",
  },
};
