//     This code was generated by the Sitrep contract error-code codegen
//     (Sitrep.Contract.RtConfig.EmitErrorCodeMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type { ErrorCodeDeclaration } from "@ksp-gonogo/sitrep-sdk";

/**
 * The refusals Kerbalism's commands answer with that say more than a core code
 * can: each refines the root a client classifies it by.
 *
 * @category Error codes
 */
export const KerbalismErrorCodes = {
  /**
   * Kerbalism runs and transmits experiments continuously on its own, so a
   * one-shot deploy or transmit has nothing to act on.
   */
  ContinuousScience: "kerbalism.continuousScience",
  /**
   * Kerbalism is not modelling science on this vessel, so there is no file or
   * sample to act on.
   */
  ScienceNotModelled: "kerbalism.scienceNotModelled",
  /**
   * No drive beside a lab, other than the one holding it, has room for the whole
   * sample.
   */
  NoDriveSpace: "kerbalism.noDriveSpace",
  /**
   * A Kerbalism drive was asked to change a file or sample and reported that it
   * had not.
   */
  DriveRefused: "kerbalism.driveRefused",
} as const;
export type KerbalismErrorCodes = (typeof KerbalismErrorCodes)[keyof typeof KerbalismErrorCodes];

/**
 * Every code declared here, with the sentence an operator reads for it.
 *
 * @category Error codes
 */
export const KERBALISM_ERROR_CODES: readonly ErrorCodeDeclaration[] = [
  {
    id: "kerbalism.continuousScience",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "Kerbalism runs and transmits experiments on its own",
    meaning: "Kerbalism runs and transmits experiments continuously on its own, so a one-shot deploy or transmit has nothing to act on.",
  },
  {
    id: "kerbalism.scienceNotModelled",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "Kerbalism is not modelling science here",
    meaning: "Kerbalism is not modelling science on this vessel, so there is no file or sample to act on.",
  },
  {
    id: "kerbalism.noDriveSpace",
    kind: "refusal",
    refines: "limitReached",
    origin: null,
    sentence: "no drive beside a lab has room for the whole sample",
    meaning: "No drive beside a lab, other than the one holding it, has room for the whole sample.",
  },
  {
    id: "kerbalism.driveRefused",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "the Kerbalism drive did not make the change",
    meaning: "A Kerbalism drive was asked to change a file or sample and reported that it had not.",
  },
];
