//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/**
 * Every unit token the built-in payloads use.
 *
 * @category Units and values
 */
export type KnownSitrepUnit =
  | "%"
  | "1"
  | "B"
  | "GB"
  | "K"
  | "MB"
  | "MB/s"
  | "Mit"
  | "W/m²"
  | "bit"
  | "bit/s"
  | "count"
  | "dB"
  | "enum"
  | "f/day"
  | "flag"
  | "funds"
  | "g"
  | "id"
  | "isp"
  | "kB"
  | "kN"
  | "kPa"
  | "kW"
  | "kg"
  | "kg/m³"
  | "kg/s"
  | "km"
  | "m"
  | "m/s"
  | "m²"
  | "m³"
  | "m³/s²"
  | "n/a"
  | "rad"
  | "rad/s"
  | "ratio"
  | "rep"
  | "rep/day"
  | "rpm"
  | "s"
  | "science"
  | "science/MB"
  | "science/day"
  | "t"
  | "text"
  | "units"
  | "units/s"
  | "ut"
  | "°"
;

/**
 * A declared unit. OPEN on purpose.
 *
 * The known tokens above still autocomplete. Any other string is accepted
 * too, so an Uplink can declare a unit of its own.
 *
 * A consumer teaches the client what an unknown symbol MEANS by declaring it
 * in UnitDeclarations and calling registerUnit from @ksp-gonogo/sitrep-sdk.
 * Until it does, the value still renders, bare and unscaled.
 *
 * @category Units and values
 */
export type SitrepUnit = KnownSitrepUnit | (string & {});

/**
 * Declared units for one payload shape, keyed by camelCased field name.
 *
 * @category Units and values
 */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "KerbalismCrewEntry": {
    deathClockUt: "ut",
    name: "text",
    rulesAsOfKerbalismUt: "ut",
    trait: "text",
  },
  "KerbalismCrewRule": {
    degenPerSec: "units/s",
    fatalThreshold: "units",
    name: "text",
    problem: "units",
  },
  "KerbalismFeatures": {
    automation: "flag",
    comfort: "flag",
    deploy: "flag",
    habitat: "flag",
    livingSpace: "flag",
    poisoning: "flag",
    pressure: "flag",
    radiation: "flag",
    reliability: "flag",
    science: "flag",
    shielding: "flag",
    spaceWeather: "flag",
    supplies: "flag",
  },
  "KerbalismGreenhouseEntry": {
    active: "flag",
    artificial: "W/m²",
    cropResource: "text",
    ecRateMaxPerSec: "units/s",
    foodRatePerSec: "units/s",
    issue: "text",
    lampEcDrawPerSec: "units/s",
    lightToleranceWm2: "W/m²",
    natural: "W/m²",
    pressureTolerance: "ratio",
    radiationToleranceRadPerSec: "rad/s",
  },
  "KerbalismHabitat": {
    comfort: "ratio",
    livingSpace: "ratio",
    poisoning: "ratio",
    pressure: "ratio",
    shielding: "ratio",
    surface: "m²",
    volume: "m³",
  },
  "KerbalismIsruConverterExtension": {
    broken: "flag",
    capacity: "units",
    processToken: "text",
    title: "text",
    valveIndex: "count",
  },
  "KerbalismIsruDrillExtension": {
    ecRate: "units/s",
    harvestType: "text",
    issue: "text",
    sourceMassRemaining: "t",
    sourceMassThreshold: "t",
  },
  "KerbalismLifeSupport": {
    asOfKerbalismUt: "ut",
    rates: "units/s",
    ruleEnvModifiers: "1",
  },
  "KerbalismProcessDef": {
    dumpValves: "text",
    inputs: "units/s",
    modifiers: "text",
    name: "text",
    outputs: "units/s",
  },
  "KerbalismProcessEntry": {
    broken: "flag",
    capacity: "units",
    envModifier: "1",
    flightId: "id",
    resource: "text",
    running: "flag",
    title: "text",
    valveIndex: "count",
  },
  "KerbalismProfile": {
    name: "text",
  },
  "KerbalismReliabilityBudget": {
    consumed: "ratio",
    id: "id",
    kind: "enum",
    label: "text",
    limitSeconds: "s",
    usedSeconds: "s",
  },
  "KerbalismReliabilityPart": {
    condition: "enum",
    conditionDetail: "text",
    mtbfSeconds: "s",
    partId: "id",
    quality: "flag",
    redundancyGroup: "text",
    repairLevel: "count",
    repairTrait: "text",
    title: "text",
  },
  "KerbalismReliabilitySummary": {
    brokenPartCount: "count",
    coverage: "enum",
    criticalChance: "ratio",
    incentiveRedundancy: "flag",
    requireRepairKits: "flag",
    safeModeChance: "ratio",
    serviceDuePartCount: "count",
    worstMtbfSeconds: "s",
  },
  "KerbalismRepairCostItem": {
    name: "id",
    quantity: "count",
  },
  "KerbalismRepairOutcome": {
    kitsFrom: "id",
    kitsUsed: "count",
    repaired: "flag",
  },
  "KerbalismRepairPartArgs": {
    crewName: "text",
    partId: "id",
  },
  "KerbalismResource": {
    amount: "units",
    capacity: "units",
    rate: "units/s",
  },
  "KerbalismResourceDef": {
    density: "kg/m³",
    displayName: "text",
    flowMode: "text",
    flowModeOrdinal: "enum",
    isSupply: "flag",
    lowThreshold: "ratio",
  },
  "KerbalismRuleDef": {
    breakdown: "flag",
    degeneration: "units/s",
    fatalThreshold: "units",
    input: "text",
    interval: "s",
    modifiers: "text",
    name: "text",
    output: "text",
    rate: "units",
    ratePerSecond: "units/s",
  },
  "KerbalismScienceBreakdownExt": {
    percentCollectedTotal: "ratio",
    scienceCollectedInFlight: "science",
    scienceRemainingTotal: "science",
    timesCompleted: "count",
  },
  "KerbalismScienceExperimentExt": {
    analyze: "flag",
    dataSizeMB: "MB",
    kind: "id",
    sampleMass: "t",
    sampleSlotsTotal: "count",
    sampleSlotsUsed: "count",
    sciencePerMB: "science/MB",
    sendFlagged: "flag",
    storageCapacityMB: "MB",
    storageUsedMB: "MB",
    transmitRateMBps: "MB/s",
    transmitting: "flag",
  },
  "KerbalismScienceInstrumentExt": {
    bodyCoveragePercent: "%",
    dataRateMBps: "MB/s",
    ecRate: "units/s",
    expStatus: "id",
    issue: "text",
    kind: "id",
    powerDisabled: "flag",
    prodFactor: "ratio",
    remainingSampleMass: "t",
    runningState: "id",
    scanning: "flag",
  },
  "KerbalismScienceLabExt": {
    analysisRateMBps: "MB/s",
    effectiveRateMBps: "MB/s",
    status: "id",
  },
  "KerbalismSpaceWeather": {
    blackout: "flag",
    habitatRadiationRadPerSecond: "rad/s",
    inSunlight: "flag",
    innerBelt: "flag",
    magnetosphere: "flag",
    outerBelt: "flag",
    radiationRadPerSecond: "rad/s",
    shieldingAmount: "units",
    shieldingCapacity: "units",
    stormEjectionSpeed: "m/s",
    stormInProgress: "flag",
    stormIncoming: "flag",
  },
  "KerbalismStarInfo": {
    "direction.x": "1",
    "direction.y": "1",
    "direction.z": "1",
    distance: "m",
    star: "text",
  },
  "KerbalismStormEntry": {
    dist: "m",
    star: "text",
    stormDuration: "s",
    stormState: "count",
    stormTime: "ut",
    targetKind: "enum",
    targetName: "text",
  },
  "KerbalismSubjectActionArgs": {
    subjectId: "id",
  },
  "KerbalismSubjectFlagArgs": {
    flag: "flag",
    subjectId: "id",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "kerbalism.crew": {
    deathClockUt: "ut",
    name: "text",
    rulesAsOfKerbalismUt: "ut",
    trait: "text",
  },
  "kerbalism.features": {
    automation: "flag",
    comfort: "flag",
    deploy: "flag",
    habitat: "flag",
    livingSpace: "flag",
    poisoning: "flag",
    pressure: "flag",
    radiation: "flag",
    reliability: "flag",
    science: "flag",
    shielding: "flag",
    spaceWeather: "flag",
    supplies: "flag",
  },
  "kerbalism.lifesupport": {
    asOfKerbalismUt: "ut",
    rates: "units/s",
    ruleEnvModifiers: "1",
  },
  "kerbalism.profile": {
    name: "text",
  },
  "kerbalism.reliability": {
    brokenPartCount: "count",
    coverage: "enum",
    criticalChance: "ratio",
    incentiveRedundancy: "flag",
    requireRepairKits: "flag",
    safeModeChance: "ratio",
    serviceDuePartCount: "count",
    worstMtbfSeconds: "s",
  },
  "kerbalism.reliabilityParts": {
    condition: "enum",
    conditionDetail: "text",
    mtbfSeconds: "s",
    partId: "id",
    quality: "flag",
    redundancyGroup: "text",
    repairLevel: "count",
    repairTrait: "text",
    title: "text",
  },
  "kerbalism.spaceweather": {
    blackout: "flag",
    habitatRadiationRadPerSecond: "rad/s",
    inSunlight: "flag",
    innerBelt: "flag",
    magnetosphere: "flag",
    outerBelt: "flag",
    radiationRadPerSecond: "rad/s",
    shieldingAmount: "units",
    shieldingCapacity: "units",
    stormEjectionSpeed: "m/s",
    stormInProgress: "flag",
    stormIncoming: "flag",
  },
};

/**
 * The nested payload shape each complex field holds, by its interface name.
 *
 * @category Units and values
 */
export type ShapesByField = Readonly<Record<string, string>>;

/**
 * Which fields hold ANOTHER payload shape, and which one.
 *
 * The unit maps above are flat: they describe one shape's own fields and
 * stop there. That was enough while a unit was only ever looked up, and
 * wrong once the runtime started WRAPPING decoded payloads, because a
 * nested shape's declared units were unreachable from the parent's entry.
 * `vessel.target.orbit.sma` is the plain case: the contract types it as
 * Value<"m">, and without this it arrived as a bare number.
 *
 * An entry names the ELEMENT type and says how many of it the field holds:
 * a bare name is one, a leading `*` a string-keyed DICTIONARY of them, and
 * a trailing `[]` a LIST of them. The element is what a consumer indexes
 * into either way, which is the same convention the topic unit map follows
 * for an array Topic.
 *
 * The plural markers are what separate a path something can SAMPLE from a
 * path that only names a field of an element. `contracts.active.agent` is
 * the second kind: `career.status.contracts.active` is an array, so no
 * sample reaches an `agent` under it.
 */
export const GENERATED_TYPE_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "KerbalismCrewEntry": {
    rules: "KerbalismCrewRule[]",
  },
  "KerbalismLifeSupport": {
    greenhouses: "KerbalismGreenhouseEntry[]",
    habitat: "KerbalismHabitat",
    processes: "KerbalismProcessEntry[]",
  },
  "KerbalismProfile": {
    processes: "KerbalismProcessDef[]",
    resources: "*KerbalismResourceDef",
    rules: "KerbalismRuleDef[]",
  },
  "KerbalismReliabilityPart": {
    budgets: "KerbalismReliabilityBudget[]",
    repairCost: "KerbalismRepairCostItem[]",
  },
  "KerbalismSpaceWeather": {
    stars: "KerbalismStarInfo[]",
    storms: "KerbalismStormEntry[]",
  },
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "kerbalism.crew": {
    rules: "KerbalismCrewRule[]",
  },
  "kerbalism.lifesupport": {
    greenhouses: "KerbalismGreenhouseEntry[]",
    habitat: "KerbalismHabitat",
    processes: "KerbalismProcessEntry[]",
  },
  "kerbalism.profile": {
    processes: "KerbalismProcessDef[]",
    resources: "*KerbalismResourceDef",
    rules: "KerbalismRuleDef[]",
  },
  "kerbalism.reliabilityParts": {
    budgets: "KerbalismReliabilityBudget[]",
    repairCost: "KerbalismRepairCostItem[]",
  },
  "kerbalism.spaceweather": {
    stars: "KerbalismStarInfo[]",
    storms: "KerbalismStormEntry[]",
  },
};

/**
 * How each `enum` field reads as a word, keyed by camelCased field name:
 * the enum whose ordinal the wire carries (see GENERATED_ENUM_MEMBERS), or
 * null for a field whose value is already the member's name.
 */
export type EnumsByField = Readonly<Record<string, string | null>>;

/** Keyed by the generated interface name in ./contract.ts. */
export const GENERATED_TYPE_ENUMS: Readonly<Record<string, EnumsByField>> = {
  "KerbalismReliabilityBudget": {
    kind: null,
  },
  "KerbalismReliabilityPart": {
    condition: null,
  },
  "KerbalismReliabilitySummary": {
    coverage: null,
  },
  "KerbalismResourceDef": {
    flowModeOrdinal: "KspResourceFlowMode",
  },
  "KerbalismStormEntry": {
    targetKind: "KerbalismStormTargetKind",
  },
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_ENUMS: Readonly<Record<string, EnumsByField>> = {
  "kerbalism.reliability": {
    coverage: null,
  },
  "kerbalism.reliabilityParts": {
    condition: null,
  },
};

/** Each enum an `enum` field names, as its wire value to member name. */
export const GENERATED_ENUM_MEMBERS: Readonly<Record<string, Readonly<Record<number, string>>>> = {
  "KerbalismStormTargetKind": {
    0: "Body",
    1: "Vessel",
  },
  "KspResourceFlowMode": {
    0: "NO_FLOW",
    1: "ALL_VESSEL",
    2: "STAGE_PRIORITY_FLOW",
    3: "STACK_PRIORITY_SEARCH",
    4: "ALL_VESSEL_BALANCE",
    5: "STAGE_PRIORITY_FLOW_BALANCE",
    6: "STAGE_STACK_FLOW",
    7: "STAGE_STACK_FLOW_BALANCE",
    8: "NULL",
  },
};
