//     This code was generated by the Sitrep contract error-code codegen
//     (Sitrep.Contract.RtConfig.EmitErrorCodeMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type { ErrorCodeDeclaration } from "@ksp-gonogo/sitrep-sdk";

/**
 * The guards that refuse a Principia plan write before the plugin is called:
 * each refines the root a client classifies it by.
 *
 * @category Error codes
 */
export const PrincipiaErrorCodes = {
  /**
   * No plugin, no session, or a producer build whose write entry points were
   * never analysed. Writes fail closed to read-only.
   */
  SurfaceUnavailable: "principia.surfaceUnavailable",
  /**
   * The surface was not armed. Every plan write changes the player's saved game
   * and re-integrates on the game's own thread, so it takes a deliberate arm
   * first.
   */
  NotArmed: "principia.notArmed",
  /**
   * The struct this write passes to the plugin failed its round-trip probe, or
   * the probe has not run. A stale shape does not fail to resolve: it writes a
   * plausible wrong burn into the save.
   */
  LayoutUnverified: "principia.layoutUnverified",
  /**
   * The plugin no longer knows this vessel.
   */
  VesselUnknown: "principia.vesselUnknown",
  /**
   * The vessel holds no flight plan to edit.
   */
  NoFlightPlan: "principia.noFlightPlan",
  /**
   * A plan already exists and this write would have created a second without
   * being asked to.
   */
  PlanAlreadyExists: "principia.planAlreadyExists",
  /**
   * The vessel already holds the producer's maximum of ten plans. An eleventh
   * makes the producer's own planner window throw on every layout pass,
   * permanently, with the button that would delete it inside the part that
   * stopped rendering.
   */
  PlanSlotsFull: "principia.planSlotsFull",
  /**
   * The burn index was outside the count read in the same frame.
   */
  BurnIndexOutOfRange: "principia.burnIndexOutOfRange",
  /**
   * The burn is running right now. The plugin permits this and only the rebase
   * entry point checks, so the guard is ours.
   */
  BurnExecuting: "principia.burnExecuting",
  /**
   * The burn's manœuvring frame is one the producer's frame factory does not
   * handle, so sending the burn back would abort the game.
   */
  BurnFrameUnsupported: "principia.burnFrameUnsupported",
  /**
   * An optimisation is running on this plan and would revert the edit without
   * reporting it.
   */
  OptimisationRunning: "principia.optimisationRunning",
  /**
   * A requested value was not finite, or a Δv triple would have been.
   */
  ValueNotFinite: "principia.valueNotFinite",
  /**
   * Thrust is not positive. A zero-thrust burn has infinite duration, which the
   * producer's own singularity test does not catch: it pushes the plan's end
   * instant to infinity, spawns a thread that never terminates, and serialises
   * the infinity into the save.
   */
  ThrustNotPositive: "principia.thrustNotPositive",
  /**
   * The integrator kinds read back from the plugin were not the pair this build
   * expects, so writing them back could abort with no message. The read
   * succeeded, so this is neither unreadable nor a craft's capability.
   */
  IntegratorKindUnexpected: "principia.integratorKindUnexpected",
  /**
   * A requested integrator bound was outside the range the producer's own
   * controls offer.
   */
  IntegratorBoundsExceeded: "principia.integratorBoundsExceeded",
  /**
   * A plan cannot be created ending before it starts.
   */
  FinalTimeInPast: "principia.finalTimeInPast",
  /**
   * A field this write must set was not found on the producer's own struct, so
   * its shape is not the shape that was analysed. Nothing about the vessel was
   * established, so this is not a craft's capability.
   */
  PluginShapeChanged: "principia.pluginShapeChanged",
  /**
   * The ignition instant this write asked for had already passed by the time the
   * write arrived, which signal delay can cause with nothing done wrong at
   * either end. Distinct from `PrincipiaErrorCodes.FinalTimeInPast`, which is
   * about a plan's end and only reachable while creating one.
   */
  IgnitionInPast: "principia.ignitionInPast",
  /**
   * A composed plan that cannot be read as one: no burn list where a list was
   * required, a burn missing from the middle, more burns than a single command
   * may install, ignitions out of time order, or an end that falls before the
   * last burn. It refuses the whole plan, because a plan half-installed is a
   * trajectory nobody composed.
   */
  PlanMalformed: "principia.planMalformed",
  /**
   * A burn with no manœuvre ahead of it was asked for without the instant it
   * lights. An absent instant elsewhere means "leave it where it is", and a burn
   * with nothing ahead of it has no instant to be left at.
   */
  ComposedBurnIncomplete: "principia.composedBurnIncomplete",
  /**
   * A read a guard depends on could not be decoded from the loaded build, so the
   * guard cannot answer: whether a burn is under thrust, whether an optimisation
   * would revert the edit, or what the producer's clock reads. Refused rather
   * than permitted. Distinct from `PrincipiaErrorCodes.PluginShapeChanged`,
   * which is a field this write must set; this is a value this build could not
   * read.
   */
  GuardReadUnreadable: "principia.guardReadUnreadable",
} as const;
export type PrincipiaErrorCodes = (typeof PrincipiaErrorCodes)[keyof typeof PrincipiaErrorCodes];

/**
 * Every code declared here, with the sentence an operator reads for it.
 *
 * @category Error codes
 */
export const PRINCIPIA_ERROR_CODES: readonly ErrorCodeDeclaration[] = [
  {
    id: "principia.surfaceUnavailable",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "Principia's plan surface is not available",
    meaning: "No plugin, no session, or a producer build whose write entry points were never analysed. Writes fail closed to read-only.",
  },
  {
    id: "principia.notArmed",
    kind: "refusal",
    refines: "notClearToProceed",
    origin: null,
    sentence: "plan writes are not armed",
    meaning: "The surface was not armed. Every plan write changes the player's saved game and re-integrates on the game's own thread, so it takes a deliberate arm first.",
  },
  {
    id: "principia.layoutUnverified",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "this Principia build's plan layout is not verified",
    meaning: "The struct this write passes to the plugin failed its round-trip probe, or the probe has not run. A stale shape does not fail to resolve: it writes a plausible wrong burn into the save.",
  },
  {
    id: "principia.vesselUnknown",
    kind: "refusal",
    refines: "noVessel",
    origin: null,
    sentence: "Principia does not know this vessel",
    meaning: "The plugin no longer knows this vessel.",
  },
  {
    id: "principia.noFlightPlan",
    kind: "refusal",
    refines: "wrongState",
    origin: null,
    sentence: "the vessel has no flight plan",
    meaning: "The vessel holds no flight plan to edit.",
  },
  {
    id: "principia.planAlreadyExists",
    kind: "refusal",
    refines: "wrongState",
    origin: null,
    sentence: "the vessel already has a flight plan",
    meaning: "A plan already exists and this write would have created a second without being asked to.",
  },
  {
    id: "principia.planSlotsFull",
    kind: "refusal",
    refines: "limitReached",
    origin: null,
    sentence: "the vessel already holds ten flight plans",
    meaning: "The vessel already holds the producer's maximum of ten plans. An eleventh makes the producer's own planner window throw on every layout pass, permanently, with the button that would delete it inside the part that stopped rendering.",
  },
  {
    id: "principia.burnIndexOutOfRange",
    kind: "refusal",
    refines: "notFound",
    origin: null,
    sentence: "the plan has no burn at that position",
    meaning: "The burn index was outside the count read in the same frame.",
  },
  {
    id: "principia.burnExecuting",
    kind: "refusal",
    refines: "notClearToProceed",
    origin: null,
    sentence: "that burn is executing",
    meaning: "The burn is running right now. The plugin permits this and only the rebase entry point checks, so the guard is ours.",
  },
  {
    id: "principia.burnFrameUnsupported",
    kind: "refusal",
    refines: "capabilityMismatch",
    origin: null,
    sentence: "Principia cannot take that burn's frame back",
    meaning: "The burn's manœuvring frame is one the producer's frame factory does not handle, so sending the burn back would abort the game.",
  },
  {
    id: "principia.optimisationRunning",
    kind: "refusal",
    refines: "notClearToProceed",
    origin: null,
    sentence: "an optimisation is running on the plan",
    meaning: "An optimisation is running on this plan and would revert the edit without reporting it.",
  },
  {
    id: "principia.valueNotFinite",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "a value was not a finite number",
    meaning: "A requested value was not finite, or a Δv triple would have been.",
  },
  {
    id: "principia.thrustNotPositive",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "the thrust is not positive",
    meaning: "Thrust is not positive. A zero-thrust burn has infinite duration, which the producer's own singularity test does not catch: it pushes the plan's end instant to infinity, spawns a thread that never terminates, and serialises the infinity into the save.",
  },
  {
    id: "principia.integratorKindUnexpected",
    kind: "refusal",
    refines: "modeUnavailable",
    origin: null,
    sentence: "the plan's integrators are not a pair this Uplink expects",
    meaning: "The integrator kinds read back from the plugin were not the pair this build expects, so writing them back could abort with no message. The read succeeded, so this is neither unreadable nor a craft's capability.",
  },
  {
    id: "principia.integratorBoundsExceeded",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "an integrator bound is outside what Principia offers",
    meaning: "A requested integrator bound was outside the range the producer's own controls offer.",
  },
  {
    id: "principia.finalTimeInPast",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "the plan would end before it starts",
    meaning: "A plan cannot be created ending before it starts.",
  },
  {
    id: "principia.pluginShapeChanged",
    kind: "refusal",
    refines: "unreadable",
    origin: null,
    sentence: "this Principia build's plan is not shaped as this Uplink expects",
    meaning: "A field this write must set was not found on the producer's own struct, so its shape is not the shape that was analysed. Nothing about the vessel was established, so this is not a craft's capability.",
  },
  {
    id: "principia.ignitionInPast",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "the ignition time had already passed",
    meaning: "The ignition instant this write asked for had already passed by the time the write arrived, which signal delay can cause with nothing done wrong at either end. Distinct from `PrincipiaErrorCodes.FinalTimeInPast`, which is about a plan's end and only reachable while creating one.",
  },
  {
    id: "principia.planMalformed",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "the composed plan cannot be read as one plan",
    meaning: "A composed plan that cannot be read as one: no burn list where a list was required, a burn missing from the middle, more burns than a single command may install, ignitions out of time order, or an end that falls before the last burn. It refuses the whole plan, because a plan half-installed is a trajectory nobody composed.",
  },
  {
    id: "principia.composedBurnIncomplete",
    kind: "refusal",
    refines: "range",
    origin: null,
    sentence: "a first burn needs the time it lights",
    meaning: "A burn with no manœuvre ahead of it was asked for without the instant it lights. An absent instant elsewhere means \"leave it where it is\", and a burn with nothing ahead of it has no instant to be left at.",
  },
  {
    id: "principia.guardReadUnreadable",
    kind: "refusal",
    refines: "unreadable",
    origin: null,
    sentence: "a value a write guard needs would not read",
    meaning: "A read a guard depends on could not be decoded from the loaded build, so the guard cannot answer: whether a burn is under thrust, whether an optimisation would revert the edit, or what the producer's clock reads. Refused rather than permitted. Distinct from `PrincipiaErrorCodes.PluginShapeChanged`, which is a field this write must set; this is a value this build could not read.",
  },
];
