//     This code was generated by the Sitrep contract unit-map codegen
//     (Sitrep.Contract.RtConfig.EmitUnitMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepUnit]-tagged property in
// Sitrep.Contract. Keys are the camelCased field names as they appear in
// ./contract.ts. A field ABSENT here has no declared unit yet (the default),
// which is not the same as being dimensionless: dimensionless is the
// explicit "1" token.

/** Every token first-party payloads use (Sitrep.Contract.Units). */
export type KnownSitrepUnit =
  | "%"
  | "1"
  | "K"
  | "Mit"
  | "W/m²"
  | "bit"
  | "bit/s"
  | "count"
  | "dB"
  | "enum"
  | "f/day"
  | "flag"
  | "funds"
  | "g"
  | "h"
  | "id"
  | "isp"
  | "kN"
  | "kPa"
  | "kW"
  | "kg"
  | "kg/m³"
  | "kg/s"
  | "km"
  | "m"
  | "m/s"
  | "m²"
  | "m³"
  | "m³/s²"
  | "n/a"
  | "rad"
  | "rad/s"
  | "ratio"
  | "rep"
  | "rep/day"
  | "rpm"
  | "s"
  | "science"
  | "science/day"
  | "t"
  | "text"
  | "units"
  | "units/s"
  | "ut"
  | "°"
  | "°/h"
;

/**
 * A declared unit. OPEN on purpose.
 *
 * The known tokens above still autocomplete, and a typo in first-party
 * code is still caught at codegen time by the catalog check. The open arm
 * exists because a third-party Uplink CANNOT add to Sitrep.Contract.Units:
 * it is a const-string class compiled into the contract assembly. Closing
 * this union would therefore have meant an Uplink could never declare a
 * unit at all, which contradicts third parties being first-class.
 *
 * A consumer teaches the client what an unknown symbol MEANS by declaring it
 * in UnitDeclarations and calling registerUnit from @ksp-gonogo/sitrep-sdk.
 * Until it does, the value still renders, bare and unscaled.
 */
export type SitrepUnit = KnownSitrepUnit | (string & {});

/** Declared units for one payload shape, keyed by camelCased field name. */
export type UnitsByField = Readonly<Record<string, SitrepUnit>>;

/**
 * Keyed by the generated interface name in ./contract.ts. Covers NESTED
 * payload shapes that no Topic names directly.
 */
export const GENERATED_TYPE_UNITS: Readonly<Record<string, UnitsByField>> = {
  "PrincipiaAnalysis": {
    sampledAtUt: "ut",
    vesselId: "id",
  },
  "PrincipiaAngleInterval": {
    max: "°",
    min: "°",
  },
  "PrincipiaBurnEditArgs": {
    burnIndex: "count",
    deltaVBinormal: "m/s",
    deltaVNormal: "m/s",
    deltaVTangent: "m/s",
    ignitionUt: "ut",
    inertiallyFixed: "flag",
    requestId: "id",
    vesselId: "id",
  },
  "PrincipiaBurnRemoveArgs": {
    burnIndex: "count",
    requestId: "id",
    vesselId: "id",
  },
  "PrincipiaCoastAnalysis": {
    endsAtUt: "ut",
    index: "count",
    startsAtUt: "ut",
  },
  "PrincipiaComposedBurn": {
    deltaVBinormal: "m/s",
    deltaVNormal: "m/s",
    deltaVTangent: "m/s",
    ignitionUt: "ut",
    inertiallyFixed: "flag",
  },
  "PrincipiaLengthInterval": {
    max: "m",
    min: "m",
  },
  "PrincipiaOrbitAnalysis": {
    anomalisticPeriodSeconds: "s",
    elementsEpochUt: "ut",
    elementsPresent: "flag",
    firstCollisionRiskUt: "ut",
    firstCollisionUt: "ut",
    firstReentryUt: "ut",
    gravitationallyBound: "flag",
    lowestAltitudeMetres: "m",
    missionDurationSeconds: "s",
    nodalPeriodSeconds: "s",
    nodalPrecessionDegreesPerHour: "°/h",
    primaryBody: "text",
    primaryIndex: "count",
    progressOfNextAnalysis: "ratio",
    recurrenceCycleRotations: "count",
    recurrenceEquatorialShiftDegrees: "°",
    recurrenceGridIntervalDegrees: "°",
    recurrenceRevolutions: "count",
    recurrenceRevolutionsPerRotation: "count",
    recurrenceSubcycleRotations: "count",
    siderealPeriodSeconds: "s",
  },
  "PrincipiaPlan": {
    actualFinalTimeUt: "ut",
    anomalousBurnCount: "count",
    desiredFinalTimeUt: "ut",
    firstFutureBurnIndex: "count",
    initialTimeUt: "ut",
    optimisationRunning: "flag",
    planCount: "count",
    planExists: "flag",
    planIntegrated: "flag",
    reachedDeadline: "flag",
    sampledAtUt: "ut",
    selectedPlan: "count",
    statusError: "enum",
    statusMessage: "text",
    vesselId: "id",
  },
  "PrincipiaPlanArmArgs": {
    requestId: "id",
    vesselId: "id",
  },
  "PrincipiaPlanHorizonArgs": {
    desiredFinalTimeUt: "ut",
    requestId: "id",
    vesselId: "id",
  },
  "PrincipiaPlanIntegrator": {
    generalizedIntegratorKind: "enum",
    integratorKind: "enum",
    lengthToleranceMetres: "m",
    maxSteps: "count",
    speedToleranceMetresPerSecond: "m/s",
  },
  "PrincipiaPlanIntegratorArgs": {
    lengthToleranceMetres: "m",
    maxSteps: "count",
    requestId: "id",
    speedToleranceMetresPerSecond: "m/s",
    vesselId: "id",
  },
  "PrincipiaPlanSendArgs": {
    composedAtViewUt: "ut",
    desiredFinalTimeUt: "ut",
    observedAtUt: "ut",
    requestId: "id",
    vesselId: "id",
  },
  "PrincipiaPlanSlotArgs": {
    finalTimeUt: "ut",
    requestId: "id",
    vesselId: "id",
  },
  "PrincipiaPlanWriteReceipt": {
    refusalDetail: "text",
    replayed: "flag",
    requestId: "id",
    statusError: "enum",
    statusMessage: "text",
  },
  "PrincipiaPlannedBurn": {
    anomalous: "flag",
    centreBody: "text",
    coordinateSystem: "enum",
    cutoffUt: "ut",
    deltaV: "m/s",
    deltaVBinormal: "m/s",
    deltaVNormal: "m/s",
    deltaVTangent: "m/s",
    durationSeconds: "s",
    executing: "flag",
    finalMassTons: "t",
    frameEditable: "flag",
    frameType: "enum",
    ignitionUt: "ut",
    index: "count",
    inertiallyFixed: "flag",
    initialMassTons: "t",
    massFlowKilogramsPerSecond: "kg/s",
    primaryBodies: "text",
    primaryBody: "text",
    secondaryBodies: "text",
    secondaryBody: "text",
    specificImpulseSeconds: "isp",
    thrustKilonewtons: "kN",
    timeToHalfDeltaVSeconds: "s",
  },
  "PrincipiaRatioInterval": {
    max: "1",
    min: "1",
  },
  "PrincipiaReferenceFrame": {
    centreBody: "text",
    primaryBodies: "text",
    primaryBody: "text",
    secondaryBodies: "text",
    secondaryBody: "text",
    selector: "text",
    targetFrameSelected: "flag",
    targetPrimaryBody: "text",
    targetVesselId: "id",
    targetVesselName: "text",
    type: "enum",
  },
  "PrincipiaSettings": {
    analysisMissionDurationRequestedSeconds: "s",
    displayPatchedConics: "flag",
    flightPlanCount: "count",
    flushThreshold: "count",
    framesHidingUnpinnedCelestials: "count",
    framesHidingUnpinnedMarkers: "count",
    groundTrackRevolution: "count",
    historyLengthSeconds: "s",
    journaling: "flag",
    logThreshold: "count",
    observedAtUt: "ut",
    optimiserTargetAltitudeMetres: "m",
    optimiserTargetInclinationDegrees: "°",
    pinnedCelestials: "text",
    planActualFinalTimeUt: "ut",
    planDesiredFinalTimeUt: "ut",
    planInitialTimeUt: "ut",
    planMaxSteps: "count",
    planToleranceMetres: "m",
    pluginVersion: "text",
    predictionMaxSteps: "count",
    predictionToleranceMetres: "m",
    predictionVesselId: "id",
    readingSuspended: "flag",
    readingSuspendedReason: "text",
    recordJournalRequested: "flag",
    recurrenceAutodetect: "flag",
    recurrenceDaysPerCycle: "count",
    recurrenceRevolutionsPerCycle: "count",
    selectedFlightPlan: "count",
    selectingTargetCelestial: "flag",
    selectingTargetVessel: "flag",
    showElementGraphs: "flag",
    showManoeuvreOnNavball: "flag",
    stabilityGridMaxEccentricityMinInclination: "flag",
    stabilityGridMinEccentricityMaxInclination: "flag",
    stderrThreshold: "count",
    targetCelestialBody: "text",
    targetPinned: "flag",
    targetVesselId: "id",
    targetVesselName: "text",
    unpinnedCelestialsHiddenHere: "flag",
    unpinnedMarkersHiddenHere: "flag",
    verboseLevel: "count",
  },
  "PrincipiaWriteSurface": {
    analysedVersion: "text",
    armed: "flag",
    available: "flag",
    burnLayoutVerified: "flag",
    detectedVersion: "text",
    integratorLayoutVerified: "flag",
    reason: "text",
  },
};

/**
 * Keyed by Topic id. For an array Topic the entry describes the ELEMENT's
 * fields, which is what a consumer indexes into.
 */
export const GENERATED_TOPIC_UNITS: Readonly<Record<string, UnitsByField>> = {
  "principia.analysis": {
    sampledAtUt: "ut",
    vesselId: "id",
  },
  "principia.plan": {
    actualFinalTimeUt: "ut",
    anomalousBurnCount: "count",
    desiredFinalTimeUt: "ut",
    firstFutureBurnIndex: "count",
    initialTimeUt: "ut",
    optimisationRunning: "flag",
    planCount: "count",
    planExists: "flag",
    planIntegrated: "flag",
    reachedDeadline: "flag",
    sampledAtUt: "ut",
    selectedPlan: "count",
    statusError: "enum",
    statusMessage: "text",
    vesselId: "id",
  },
  "principia.settings": {
    analysisMissionDurationRequestedSeconds: "s",
    displayPatchedConics: "flag",
    flightPlanCount: "count",
    flushThreshold: "count",
    framesHidingUnpinnedCelestials: "count",
    framesHidingUnpinnedMarkers: "count",
    groundTrackRevolution: "count",
    historyLengthSeconds: "s",
    journaling: "flag",
    logThreshold: "count",
    observedAtUt: "ut",
    optimiserTargetAltitudeMetres: "m",
    optimiserTargetInclinationDegrees: "°",
    pinnedCelestials: "text",
    planActualFinalTimeUt: "ut",
    planDesiredFinalTimeUt: "ut",
    planInitialTimeUt: "ut",
    planMaxSteps: "count",
    planToleranceMetres: "m",
    pluginVersion: "text",
    predictionMaxSteps: "count",
    predictionToleranceMetres: "m",
    predictionVesselId: "id",
    readingSuspended: "flag",
    readingSuspendedReason: "text",
    recordJournalRequested: "flag",
    recurrenceAutodetect: "flag",
    recurrenceDaysPerCycle: "count",
    recurrenceRevolutionsPerCycle: "count",
    selectedFlightPlan: "count",
    selectingTargetCelestial: "flag",
    selectingTargetVessel: "flag",
    showElementGraphs: "flag",
    showManoeuvreOnNavball: "flag",
    stabilityGridMaxEccentricityMinInclination: "flag",
    stabilityGridMinEccentricityMaxInclination: "flag",
    stderrThreshold: "count",
    targetCelestialBody: "text",
    targetPinned: "flag",
    targetVesselId: "id",
    targetVesselName: "text",
    unpinnedCelestialsHiddenHere: "flag",
    unpinnedMarkersHiddenHere: "flag",
    verboseLevel: "count",
  },
};

/** The nested payload shape each complex field holds, by its interface name. */
export type ShapesByField = Readonly<Record<string, string>>;

/**
 * Which fields hold ANOTHER payload shape, and which one.
 *
 * The unit maps above are flat: they describe one shape's own fields and
 * stop there. That was enough while a unit was only ever looked up, and
 * wrong once the runtime started WRAPPING decoded payloads, because a
 * nested shape's declared units were unreachable from the parent's entry.
 * `vessel.target.orbit.sma` is the plain case: the contract types it as
 * Value<"m">, and without this it arrived as a bare number.
 *
 * An entry names the ELEMENT type and says how many of it the field holds:
 * a bare name is one, a leading `*` a string-keyed DICTIONARY of them, and
 * a trailing `[]` a LIST of them. The element is what a consumer indexes
 * into either way, which is the same convention the topic unit map follows
 * for an array Topic.
 *
 * The plural markers are what separate a path something can SAMPLE from a
 * path that only names a field of an element. `contracts.active.agent` is
 * the second kind: `career.status.contracts.active` is an array, so no
 * sample reaches an `agent` under it.
 */
export const GENERATED_TYPE_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "PrincipiaAnalysis": {
    coasts: "PrincipiaCoastAnalysis[]",
    orbit: "PrincipiaOrbitAnalysis",
  },
  "PrincipiaCoastAnalysis": {
    analysis: "PrincipiaOrbitAnalysis",
  },
  "PrincipiaOrbitAnalysis": {
    ascendingCrossingDegrees: "PrincipiaAngleInterval",
    ascendingNodeSolarTimeDegrees: "PrincipiaAngleInterval",
    descendingCrossingDegrees: "PrincipiaAngleInterval",
    descendingNodeSolarTimeDegrees: "PrincipiaAngleInterval",
    meanApoapsisAltitudeMetres: "PrincipiaLengthInterval",
    meanArgumentOfPeriapsisDegrees: "PrincipiaAngleInterval",
    meanEccentricity: "PrincipiaRatioInterval",
    meanInclinationDegrees: "PrincipiaAngleInterval",
    meanLongitudeOfAscendingNodeDegrees: "PrincipiaAngleInterval",
    meanPeriapsisAltitudeMetres: "PrincipiaLengthInterval",
    meanSemimajorAxisMetres: "PrincipiaLengthInterval",
  },
  "PrincipiaPlan": {
    burns: "PrincipiaPlannedBurn[]",
    integrator: "PrincipiaPlanIntegrator",
    writeSurface: "PrincipiaWriteSurface",
  },
  "PrincipiaPlanSendArgs": {
    burns: "PrincipiaComposedBurn[]",
  },
  "PrincipiaPlanWriteReceipt": {
    plan: "PrincipiaPlan",
  },
  "PrincipiaSettings": {
    burnFrames: "PrincipiaReferenceFrame[]",
    plottingFrame: "PrincipiaReferenceFrame",
  },
};

/** The same, keyed by Topic id. */
export const GENERATED_TOPIC_SHAPES: Readonly<Record<string, ShapesByField>> = {
  "principia.analysis": {
    coasts: "PrincipiaCoastAnalysis[]",
    orbit: "PrincipiaOrbitAnalysis",
  },
  "principia.plan": {
    burns: "PrincipiaPlannedBurn[]",
    integrator: "PrincipiaPlanIntegrator",
    writeSurface: "PrincipiaWriteSurface",
  },
  "principia.settings": {
    burnFrames: "PrincipiaReferenceFrame[]",
    plottingFrame: "PrincipiaReferenceFrame",
  },
};
