//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

/**
* The `aero.state` channel: the aerodynamic state of the active vessel, as
* computed by the full-fidelity aerodynamics model the player has installed.
* Produced by `FerramAerospaceResearchUplink`, which reads Ferram Aerospace
* Research's per-vessel `VesselFlightInfo` by reflection.
*
* **This is aerodynamic state, not atmospheric state.** Mach number, dynamic
* pressure, density and the temperatures stay on `vessel.flight` and are
* correct there even with FAR installed: FAR's own flight-data window reads
* the stock dynamic pressure, and its integrator registration overrides forces
* and exposed areas rather than the atmosphere. What no channel carried before
* this one is the vessel's ATTITUDE TO THE AIRFLOW and what that attitude is
* costing it: angle of attack, sideslip, how much of the wing is stalled, the
* lift and drag it is producing, and the two figures a descent is judged by.
*
* **Every field is nullable, and absence is load-bearing.** An aircraft with
* no aerodynamic reading is not an aircraft at zero angle of attack, and a
* rocket with no wings has no stall fraction rather than a stall fraction of
* zero. The mod half computes several of these as division results that are
* undefined in exactly the states an operator most wants a straight answer in
* (a wingless craft, a vacuum coast, a vehicle sitting on the pad), so each is
* published only where it is defined; see `AeroCapture`, which names the
* condition per field.
*
* A TS-shape-only typing/codegen marker: the uplink hand-builds the dict and
* `JsonWriter` walks that live tree, so this POCO never serializes. Classified
* `DelayRole.Delayed` (a per-vessel telemetry fact, subject to the
* reveal-gate); the bare `aero.available` presence primitive is
* `DelayRole.TrueNow` and declared client-side.
*/
export interface AeroState
{
	/**
	* Angle between the airflow and the vessel's own longitudinal axis, in the
	* pitch plane. The number an ascent is flown to and a re-entry is held on, and
	* the one no channel carried before.
	*/
	angleOfAttack?: Value<"°">;
	/** Angle between the airflow and the vessel's plane of symmetry, in yaw. */
	sideslip?: Value<"°">;
	/**
	* How much of the vessel's wing area is stalled, weighted by area: 0 is fully
	* attached flow, 1 is every wing stalled. Absent on a craft with no
	* aerodynamic wing surfaces at all, which is most rockets, because the
	* quantity is a fraction OF wing area and there is none.
	*/
	stallFraction?: Value<"ratio">;
	/** Whole-vessel lift coefficient, referenced to `AeroState.referenceArea`. */
	liftCoefficient?: Value<"1">;
	/** Whole-vessel drag coefficient, referenced to `AeroState.referenceArea`. */
	dragCoefficient?: Value<"1">;
	/**
	* Lift over drag: how far the vessel travels per unit of height it gives up,
	* and the figure a glide or a lifting entry is flown by.
	*/
	liftToDragRatio?: Value<"1">;
	/**
	* The area the two coefficients above are referenced to: total wing area on a
	* winged craft, otherwise the maximum cross-section the aerodynamics model
	* voxelised. Published because a coefficient without its reference area is not
	* comparable to anything, including the same vessel after staging. Read it
	* against `AeroState.aeroModelValid`: with neither wings nor a current
	* voxelisation the model substitutes one square metre, and the coefficients
	* beside it are then referenced to a placeholder.
	*/
	referenceArea?: Value<"m²">;
	/** Total aerodynamic lift, perpendicular to the airflow. */
	liftForce?: Value<"kN">;
	/** Total aerodynamic drag, along the airflow. */
	dragForce?: Value<"kN">;
	/**
	* Indicated airspeed: what a pitot tube on this vehicle would read, from the
	* stagnation pressure at the current Mach and ambient pressure. The speed an
	* airframe's limits are written against, unlike the surface speed on
	* `vessel.flight`.
	*/
	indicatedAirspeed?: Value<"m/s">;
	/**
	* Equivalent airspeed: surface speed scaled by the square root of density
	* ratio to sea level, so a given value means the same dynamic pressure at any
	* altitude.
	*/
	equivalentAirspeed?: Value<"m/s">;
	/**
	* Terminal velocity at the current attitude, altitude and mass: the speed at
	* which drag balances weight. Absent while the vessel produces no drag to
	* balance against, which includes every vacuum coast.
	*/
	terminalVelocity?: Value<"m/s">;
	/**
	* Ballistic coefficient: mass over drag area. Low decelerates high and early,
	* high drives the deceleration deeper into the atmosphere, which is what makes
	* it the number an entry corridor is judged on.
	*/
	ballisticCoefficient?: Value<"kg/m²">;
	/**
	* Specific excess power: thrust less drag, per unit mass, at the current
	* speed. Positive means the vehicle can still climb or accelerate on the power
	* it has; crossing to negative is where an X-plane's climb stops.
	*/
	specificExcessPower?: Value<"W/kg">;
	/**
	* Whether the aerodynamics model's voxelisation of this vessel is current.
	* False after a stage separation, a deployment or a docking until the model
	* has re-run, during which every coefficient above still describes the
	* PREVIOUS shape. It is a qualifier on the readings beside it rather than a
	* reading of its own, which is why it stays present when they go absent.
	*/
	aeroModelValid?: boolean;
}
