//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface ScanSensorEntry
{
	type?: number;
	fov?: Value<"°">;
	minAlt?: Value<"m">;
	maxAlt?: Value<"m">;
	bestAlt?: Value<"m">;
	inRange?: boolean;
	bestRange?: boolean;
}
export interface ScanTrackColor
{
	r?: Value<"count">;
	g?: Value<"count">;
	b?: Value<"count">;
	a?: Value<"count">;
}
export interface ScanningVesselEntry
{
	vesselId?: string;
	vesselName?: string;
	body?: string;
	subLatitude?: Value<"°">;
	subLongitude?: Value<"°">;
	altitude?: Value<"m">;
	sensors?: ScanSensorEntry[];
	groundTrackWidthDeg?: Value<"°">;
	groundTrackLonHalfDeg?: Value<"°">;
	trackColor?: ScanTrackColor;
}
export interface ScanScienceEntry
{
	partId?: string;
	partTitle?: string;
	expId?: string;
	title?: string;
	deployed?: boolean;
	hasData?: boolean;
	rerunnable?: boolean;
	inoperable?: boolean;
}
export interface ScanAnomalyEntry
{
	name?: string;
	latitude?: Value<"°">;
	longitude?: Value<"°">;
	known?: boolean;
	detail?: boolean;
}
