//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface ScanSensorEntry
{
	type?: number | null;
	fov?: Value<"°"> | null;
	minAlt?: Value<"m"> | null;
	maxAlt?: Value<"m"> | null;
	bestAlt?: Value<"m"> | null;
	inRange?: boolean | null;
	bestRange?: boolean | null;
}
export interface ScanTrackColor
{
	r?: Value<"count"> | null;
	g?: Value<"count"> | null;
	b?: Value<"count"> | null;
	a?: Value<"count"> | null;
}
export interface ScanningVesselEntry
{
	vesselId?: string;
	vesselName?: string;
	body?: string;
	subLatitude?: Value<"°"> | null;
	subLongitude?: Value<"°"> | null;
	altitude?: Value<"m"> | null;
	sensors?: ScanSensorEntry[];
	groundTrackWidthDeg?: Value<"°"> | null;
	groundTrackLonHalfDeg?: Value<"°"> | null;
	trackColor?: ScanTrackColor;
}
export interface ScanScienceEntry
{
	partId?: string;
	partTitle?: string;
	expId?: string;
	title?: string;
	deployed?: boolean | null;
	hasData?: boolean | null;
	rerunnable?: boolean | null;
	inoperable?: boolean | null;
}
export interface ScanAnomalyEntry
{
	name?: string;
	latitude?: Value<"°"> | null;
	longitude?: Value<"°"> | null;
	known?: boolean | null;
	detail?: boolean | null;
}
