//     This code was generated by the Sitrep contract topic-map codegen
//     (Sitrep.Contract.RtConfig.EmitTopicMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepTopic]-tagged payload type in
// Sitrep.Contract: the attribute's TopicId is the map key and the tagged
// type's generated interface (its plain C# name in ./contract.ts) is the
// value, with `[]` appended for the IsArray channels whose payload is a
// bare JSON array of the element type.
//
// THIS IS NOT A LIST OF EVERY TOPIC ON THE WIRE, and it cannot become one.
// A DYNAMIC namespace (`fleet.`, `silence.`, `currency.`, vessel part-actions,
// and an Uplink's own) is registered at RUNTIME through
// `IUplinkHost.RegisterDynamicNamespace` and materialises its topics per
// subject, so no [SitrepTopic]-tagged type exists for reflection to find and
// nothing about it appears below. Asking this file "is there per-vessel X"
// gets a confident no for a topic that has been published all along:
// `fleet.<guid>.orbit` was surveyed as missing that way. To enumerate the
// dynamic half, grep the mod for `RegisterDynamicNamespace` instead.

import type {
  ScanScienceEntry,
  ScanningVesselEntry,
} from "./contract.js";

export interface GeneratedTopicPayloadMap {
  "scansat.scanningVessels": ScanningVesselEntry[];
  "scansat.science": ScanScienceEntry[];
}

export const GENERATED_TOPIC_IDS = [
  "scansat.scanningVessels",
  "scansat.science",
] as const;
