// <auto-generated> Regenerated by mod/scripts/bake-client-hash.mjs at release build. DO NOT EDIT.
// The sha256 of the client bundle this DLL was released with. Empty in dev (no release
// bundle hashed yet) → Manifest.ExpectedClientHash stays null → the loader records the
// mod-hash arm as pending (two-way index==bytes fallback).
namespace Gonogo.ScansatUplink
{
    internal static class ExpectedClientHash
    {
        public const string Value = "";
    }
}
