// <auto-generated> Written by tooling/bake-client-source.mjs. DO NOT EDIT.
namespace Gonogo.ScansatUplink
{
    internal static class Provenance
    {
        public const string Name = "SCANsat";
        public const string Author = "Jon Pepler";
        public const string Repo = "https://github.com/ksp-gonogo/gonogo-uplinks";
    }
}
