//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

/**
* One kerbcast camera as it appears on the `kerbcast.cameras` channel, a bare
* JSON array of these.
*
* Sourced by reflecting the running kerbcast plugin's public
* `Kerbcast.KerbcastControl` static facade (never a compile-time reference:
* kerbcast is CC-BY-NC-SA-4.0, so the arm's-length reflection pattern is
* mandatory; see `GonogoKerbcastUplink.csproj`'s header). Every field below is
* read off kerbcast's `KerbcastCameraView`, except the docking fields, which
* this Uplink DERIVES from the stock KSP `Part` the view carries.
*
* R7 typed-absence discipline: every field is nullable. A camera whose pan
* bounds could not be read carries `null`, never a 0 that a consumer would
* read as a real "centred, no travel" limit.
*/
export interface KerbcastCameraEntry
{
	/**
	* kerbcast's own camera handle (`KerbcastCameraView.FlightId`): the id every
	* kerbcast command and the WebRTC `subscribe` take. NOTE this is NOT reliably
	* a KSP part id: kerbcast synthesises a hash for the 2nd+ camera module on a
	* multi-camera part. Use `KerbcastCameraEntry.partId` when you want part
	* identity; use this when you want to talk to kerbcast.
	*/
	cameraId?: number;
	/**
	* The real stock-KSP `Part.flightID` the camera is mounted on
	* (`KerbcastCameraView.PartFlightId`): the join key onto `vessel.parts`. Null
	* when the camera's part could not be read.
	*/
	partId?: number;
	/**
	* kerbcast's camera name. NOT unique: Hullcam's docking-port patch names every
	* docking-port camera "NavCam", which is precisely why
	* `KerbcastCameraEntry.isDockingCamera` is derived from the part's modules
	* rather than sniffed from this string.
	*/
	cameraName?: string;
	/** The part's internal name (`Part.partInfo.name`), e.g. `DC.TurretCam`. */
	partName?: string;
	/** The part's display title, e.g. `Clamp-O-Tron Docking Port Jr.`. */
	partTitle?: string;
	/** The vessel this camera is on, as `vessel:<guid>`. Null when unreadable. */
	vesselId?: string;
	/**
	* Whether the camera can zoom, kerbcast runtime-detects this from the part
	* type.
	*/
	supportsZoom?: boolean;
	/**
	* Whether the camera can pan. kerbcast derives this from a hardcoded per-part
	* capability table, so it is false for most stock camera parts.
	*/
	supportsPan?: boolean;
	/** Current field of view, degrees. */
	fieldOfView?: Value<"°">;
	/** Narrowest field of view the camera allows, degrees (fully zoomed in). */
	fieldOfViewMinimum?: Value<"°">;
	/** Widest field of view the camera allows, degrees (fully zoomed out). */
	fieldOfViewMaximum?: Value<"°">;
	/** Current pan yaw, degrees. */
	panYaw?: Value<"°">;
	/** Current pan pitch, degrees. */
	panPitch?: Value<"°">;
	/** Minimum pan yaw the camera allows, degrees. */
	panYawMinimum?: Value<"°">;
	/** Maximum pan yaw the camera allows, degrees. */
	panYawMaximum?: Value<"°">;
	/** Minimum pan pitch the camera allows, degrees. */
	panPitchMinimum?: Value<"°">;
	/** Maximum pan pitch the camera allows, degrees. */
	panPitchMaximum?: Value<"°">;
	/**
	* Whether this camera is mounted on a docking port, the operator-facing
	* question "which of my cameras can I dock with".
	*
	* DERIVED, not reported by kerbcast: kerbcast has no docking concept on its
	* wire at all. This Uplink reads the stock `ModuleDockingNode` off the
	* camera's own `Part` (the part handle kerbcast's control facade already
	* carries) and answers from the part's actual modules. That is why it is
	* trustworthy where sniffing `KerbcastCameraEntry.partTitle` for the word
	* "Docking" is not.
	*
	* Null means "could not determine" (the part was unreadable), distinct from
	* `false`, "read the part, it has no docking node".
	*/
	isDockingCamera?: boolean;
	/**
	* The docking node's `nodeType` (e.g. `size1`, `size2`) when
	* `KerbcastCameraEntry.isDockingCamera` is true, what this port can mate with.
	* Null for a non-docking camera.
	*/
	dockingPortNodeType?: string;
	/**
	* The docking node's live `state` (e.g. `Ready`, `Docked`, `Acquire`) when
	* `KerbcastCameraEntry.isDockingCamera` is true. Null for a non-docking
	* camera.
	*/
	dockingPortState?: string;
}
/**
* Args for the `kerbcast.setFieldOfView` command: zoom one camera. Delayed
* like any other craft command: a zoom is an instruction to hardware on the
* vessel, so it rides the signal-delay Courier.
*/
export interface KerbcastSetFieldOfViewArgs
{
	/** Target camera, identified by its `KerbcastCameraEntry.cameraId`. */
	cameraId: number;
	/**
	* Requested field of view, degrees. kerbcast clamps to the camera's own
	* bounds.
	*/
	fieldOfView: number;
}
/**
* Args for the `kerbcast.setPan` command: aim one camera. Absolute degrees,
* matching kerbcast's own `SetPan` facade (not a rate).
*/
export interface KerbcastSetPanArgs
{
	/** Target camera, identified by its `KerbcastCameraEntry.cameraId`. */
	cameraId: number;
	/** Requested yaw, degrees. kerbcast clamps to the camera's own bounds. */
	yaw: number;
	/** Requested pitch, degrees. kerbcast clamps to the camera's own bounds. */
	pitch: number;
}
