//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

export interface ExampleHeartbeat
{
	ut?: Value<"ut">;
	ticks?: Value<"count">;
}
