//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// GENERATED_COMMAND_RAIL below carries the same reflection's answer to the two
// questions the delay rail asks of a command: whether anything answers it, and
// whether it rides signal delay. Both are DATA a client reads, so no consumer
// holds its own list of which commands are which. What a command IS on the
// rail's other two axes is derived: a dispatch is a point, and the direction
// is which map it came out of.
//
// WHAT THE COUNT COUNTS, because a grep gets it wrong. It is one entry per
// [SitrepCommand] ATTRIBUTE, not per tagged type: SetEnabledArgs alone carries
// six. Counting `AddCommandHandler` call sites instead misses the ones the
// engine registers directly; counting `const string \w*Command\w*` catches
// CommandCentreTopic, which is a Topic; counting the strings the bundled
// clients dispatch counts what a widget presses today rather than what the
// mod accepts, and gets a quarter of the answer. Read this file.
//
// THE TOPIC MAP'S DYNAMIC CAVEAT DOES NOT CARRY OVER. There is no such
// thing as a dynamic command. `AddCommandHandler` and
// `AddVantageCommandHandler` both refuse a command with no matching
// `CommandDeclaration` in the registering uplink's Manifest, and
// `ChannelEngine` dispatches by exact dictionary key with no prefix
// matching anywhere, so a per-subject write cannot BE a command id.
//
// The subject travels in the ARGS instead, which is the fact an author
// needs: `vessel.invokePartAction` is ONE command taking a `partId`, not one
// command per part, and `science.experiment.deploy` is one taking a
// `partId`, not one per instrument. A widget composes a topic string per
// subject and never composes a command string. An Uplink's own commands
// work the same way; see that Uplink's map for its examples.
//
// So every command a client can send is nameable before the game is running,
// and this map is that set as far as the [SitrepCommand] reflection reaches.
// What it does NOT prove is that every declared command is tagged: nothing
// checks a Manifest's `Command(...)` entries against the attributes, so one
// declared and handled without a tag would be dispatchable and absent here.
//
// An earlier version of this header said the opposite of all of it, in
// arithmetic: that the count excluded a number "per CPU, per vessel, per
// compute topic". That described a mechanism which has never existed, and
// was inherited from the topic map's caveat, where it is real.

import type {
  MechJebAscentArgs,
  MechJebNoArgs,
} from "./contract.js";
import type {
  CommandResult,
} from "@ksp-gonogo/sitrep-sdk";

export interface GeneratedCommandArgsMap {
  "mechjeb.engageAscentAutopilot": MechJebAscentArgs;
  "mechjeb.executeNextNode": MechJebNoArgs;
  "mechjeb.landAtTarget": MechJebNoArgs;
}

export interface GeneratedCommandReplyMap {
  "mechjeb.engageAscentAutopilot": CommandResult;
  "mechjeb.executeNextNode": CommandResult;
  "mechjeb.landAtTarget": CommandResult;
}

/**
 * What the delay rail needs to know about a command, as DATA: a client asks
 * this table rather than carrying a list of ids it recognises.
 */
export interface GeneratedCommandRail {
  /** Whether the dispatch resolves with anything, i.e. whether an ack comes back. */
  readonly replies: boolean;
  /**
   * Whether the host holds this command for the signal delay before running it,
   * off the same `[SitrepCommand(Delayed = ...)]` the host itself dispatches by.
   */
  readonly delayed: boolean;
}

/**
 * The rail columns for every command above, keyed the same way.
 *
 * An Uplink's own commands come out of ITS map, and its client feeds them to
 * the SDK through `registerUplinkCommand`.
 *
 * `replies` reads `true` on every row here, and that is a finding rather than
 * a placeholder: `Sitrep.Contract/CommandResult.cs` rules that results are
 * always delivered, never a fire-and-forget void, so no declared command can
 * be unacked. The column exists because a client must READ that rather than
 * assume it; the day the contract declares a command that answers nothing,
 * this is where it says so.
 *
 * `delayed` is the mod's own dispatch decision, not a client-side opinion of
 * it. A `false` row runs the instant it arrives, so drawing it a countdown or
 * an in-flight queue entry would be a fiction about the operator's own order.
 */
export const GENERATED_COMMAND_RAIL = {
  "mechjeb.engageAscentAutopilot": { replies: true, delayed: true },
  "mechjeb.executeNextNode": { replies: true, delayed: true },
  "mechjeb.landAtTarget": { replies: true, delayed: true },
} as const satisfies Record<string, GeneratedCommandRail>;

export const GENERATED_COMMAND_IDS = [
  "mechjeb.engageAscentAutopilot",
  "mechjeb.executeNextNode",
  "mechjeb.landAtTarget",
] as const;
