//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Value, Vec3Of } from '@ksp-gonogo/sitrep-sdk';

/**
* The `avionics.status` channel: RP-1 controllable-mass ascent go/no-go. RP-1
* gates vehicle control by an avionics unit's tonnage limit: if the vessel's
* mass exceeds the controllable mass of its active avionics, the craft cannot
* be steered during ascent. Produced by `GonogoAvionicsUplink`, which reflects
* the RP-1 `RP0.ModuleAvionics` /
* `RP0.ProceduralAvionics.ModuleProceduralAvionics` live `CurrentMassLimit`
* (the same value `RP0.ControlLockerUtils.ShouldLock` compares) and pairs it
* with the vessel's stock total mass.
*
* A TS-shape-only typing/codegen marker: the uplink hand-builds the dict and
* `JsonWriter` walks that live tree, so this POCO never serializes. Classified
* `DelayRole.Delayed` (a per-vessel telemetry fact, subject to the
* reveal-gate); the bare `avionics.available` presence primitive is
* `DelayRole.TrueNow` and declared client-side.
*
* Declared in this Uplink's own contract slice
* (`GonogoAvionicsUplink.Contract`) rather than in `Sitrep.Contract`: no
* uplink-specific wire type may live in core, even for an in-monorepo Uplink.
* Being a real outbound READ payload, it exercises
* `RtConfig.ApplyUnitValueTypes`'s `Value<>`/`Vec3Of<>` retype end to end,
* which an inbound command-arg type does not (see
* `AvionicsRtConfig.Configure`).
*/
export interface AvionicsStatus
{
	/** True when an avionics unit is present + active on the vessel. */
	avionicsActive?: boolean;
	/**
	* Controllable-mass limit of the active avionics (tonnes), the MAX across
	* parts of each part's summed `CurrentMassLimit`, matching
	* `ControlLockerUtils.ShouldLock`. Null when no avionics is present.
	*/
	controllableMassTons?: Value<"t">;
	/** Vessel current total mass (tonnes). */
	vesselMassTons?: Value<"t">;
	/** Derived: VesselMassTons <= ControllableMassTons (the ascent go/no-go). */
	controllable?: boolean;
}
