import { value } from "@ksp-gonogo/sitrep-sdk";
import { describe, expect, it } from "vitest";
import CASES from "./__testdata__/lc-cost-cases.json" with { type: "json" };
import MODIFY_CASES from "./__testdata__/lc-modify-cases.json" with { type: "json" };
import { type LcSpec, quoteModifyComplex, quoteNewComplex } from "./lcCost.js";

/**
 * The client's transcription of RP-1's build price, held against the shipped
 * assembly's own answers.
 *
 * <para>A transcription drifts silently: it goes on agreeing with itself long
 * after it has stopped agreeing with RP-1. So the expected figures here are not
 * written by hand and not derived from this file's own arithmetic. They are
 * GENERATED by `Rp1LcCostCrossCheckTests` calling the shipped
 * `LCData.GetCostStats`, and that C# test fails if RP-1's answers move. Neither
 * side can change alone.</para>
 */
describe("quoting a complex RP-1 has not built yet", () => {
  const empty = new Map<string, number>();

  it.each(
    CASES.cases,
  )("$massMax t, $sizeMaxWidth x $sizeMaxHeight x $sizeMaxDepth m, human $humanRated, hangar $isHangar", (c) => {
    const quote = quoteNewComplex({ ...c, resources: empty } as LcSpec, {});

    expect(quote).not.toBeNull();
    /*
     * Six places, because RP-1 does its axis arithmetic in float and the pad
     * curve is a fractional power: exact equality would be asserting that two
     * languages round a transcendental identically, which is not the claim.
     */
    expect(quote?.pad).toBeCloseTo(c.pad, 6);
    expect(quote?.integration).toBeCloseTo(c.integration, 6);
    expect(quote?.total).toBeCloseTo(c.pad + c.integration, 6);
  });

  it("covers the clause a transcription is most likely to drop", () => {
    // The second term only bites above 350 t. A copy that dropped it would agree
    // with RP-1 on every case below the threshold, so the pinned set has to
    // straddle it and the difference has to be real.
    const at = CASES.cases.find((c) => c.massMax === 350 && !c.isHangar);
    const over = CASES.cases.find((c) => c.massMax === 351 && !c.isHangar);
    expect(at).toBeDefined();
    expect(over).toBeDefined();
    expect(over?.pad).toBeGreaterThan(at?.pad ?? 0);
  });

  it("refuses to quote a resource it has no price for", () => {
    // Absent is not free. RP-1 would not accept a complex handling something it
    // does not offer, and a quote that dropped it silently would name a price for
    // a complex nobody can build.
    const quote = quoteNewComplex(
      {
        humanRated: false,
        isHangar: false,
        massMax: 100,
        resources: new Map([["Kerosene", 1000]]),
        sizeMaxDepth: 10,
        sizeMaxHeight: 20,
        sizeMaxWidth: 10,
      },
      { resources: [] },
    );

    expect(quote).toBeNull();
  });

  it("prices a resource by the per-unit figure RP-1 sent", () => {
    const quote = quoteNewComplex(
      {
        humanRated: false,
        isHangar: false,
        massMax: 100,
        resources: new Map([["Kerosene", 1000]]),
        sizeMaxDepth: 10,
        sizeMaxHeight: 20,
        sizeMaxWidth: 10,
      },
      {
        resources: [
          {
            name: "Kerosene",
            padCostPerUnit: value("funds", 0.25),
          },
        ],
      },
    );

    expect(quote?.resources).toBeCloseTo(250, 9);
  });

  it("prices what RP-1 stores, which is the amount rounded up", () => {
    // RP-1 ceils to whole units before storing them, so a fractional capacity is
    // charged at the whole unit it becomes rather than the fraction typed.
    const quote = quoteNewComplex(
      {
        humanRated: false,
        isHangar: false,
        massMax: 100,
        resources: new Map([["Kerosene", 10.2]]),
        sizeMaxDepth: 10,
        sizeMaxHeight: 20,
        sizeMaxWidth: 10,
      },
      {
        resources: [{ name: "Kerosene", padCostPerUnit: value("funds", 1) }],
      },
    );

    expect(quote?.resources).toBe(11);
  });

  it("refuses to price a hangar's resources rather than using the pad's figures", () => {
    /*
     * RP-1 keeps a separate ignore mask for hangars, so the figures genuinely
     * differ, and the wire carries no hangar price because nothing can build one:
     * a career's hangar is seeded at career start and there is no renovation
     * control. Falling back to the pad's numbers would quote a complex nobody can
     * buy at a price RP-1 never charges.
     */
    const spec = {
      humanRated: false,
      isHangar: true,
      massMax: 100,
      resources: new Map([["Kerosene", 100]]),
      sizeMaxDepth: 10,
      sizeMaxHeight: 20,
      sizeMaxWidth: 10,
    };
    const padOnly = {
      resources: [{ name: "Kerosene", padCostPerUnit: value("funds", 1) }],
    };

    expect(quoteNewComplex(spec, padOnly)).toBeNull();
  });
});

/**
 * The renovation half, pinned the same way and with the same caveat: the figures
 * come out of `Rp1LcCostModel.QuoteModify`, generated by
 * `Rp1LcCostCrossCheckTests`, so neither side can move alone. What that does NOT
 * pin is either side against RP-1's own binary, which is stated in the C# file's
 * own summary and is not this test's to fix.
 */
describe("quoting a renovation of a complex the career has", () => {
  const empty = new Map<string, number>();

  it.each(
    MODIFY_CASES.cases,
  )("$massMax t to $toMassMax t, $launchPadCount pad(s), hangar $isHangar", (c) => {
    const quote = quoteModifyComplex(
      {
        humanRated: c.toHumanRated,
        isHangar: c.isHangar,
        massMax: c.toMassMax,
        resources: empty,
        sizeMaxDepth: c.toSizeMaxDepth,
        sizeMaxHeight: c.toSizeMaxHeight,
        sizeMaxWidth: c.toSizeMaxWidth,
      },
      {
        humanRated: c.humanRated,
        isHangar: c.isHangar,
        launchPadCount: c.launchPadCount,
        massMax: c.massMax,
        massOrig: c.massMax,
        resources: empty,
        sizeMaxDepth: c.sizeMaxDepth,
        sizeMaxHeight: c.sizeMaxHeight,
        sizeMaxWidth: c.sizeMaxWidth,
      },
      // RP-1's shipped 0.5, which is what the cases were generated at.
      { additionalPadCostMult: value("ratio", 0.5) },
    );

    expect(quote).not.toBeNull();
    expect(quote?.total).toBeCloseTo(c.total, 6);
    expect(quote?.isDowngrade).toBe(c.isDowngrade);
  });

  it("covers the three clauses a transcription is most likely to drop", () => {
    // Each of these is a case that agrees with a copy missing the clause, so the
    // pinned set has to contain it and the difference has to be real.
    const floored = MODIFY_CASES.cases.find(
      (c) => c.massMax === 100 && c.toMassMax === 101,
    );
    const envelopeOnly = MODIFY_CASES.cases.find(
      (c) => c.massMax === c.toMassMax && !c.isHangar,
    );
    const twoPads = MODIFY_CASES.cases.find((c) => c.launchPadCount === 2);
    const onePad = MODIFY_CASES.cases.find(
      (c) => c.launchPadCount === 1 && c.toMassMax === 180,
    );

    // The 1,000-fund floor on any tonnage movement at all.
    expect(floored?.total).toBe(1000);
    // And it is on the tonnage, not on the total: an envelope change at a fixed
    // tonnage does not get floored, it gets its own real price.
    expect(envelopeOnly?.total).toBeGreaterThan(1000);
    // Every pad the complex already has is rebuilt, so a second one costs more.
    expect(twoPads?.total).toBeGreaterThan(onePad?.total ?? 0);
  });

  it("charges for a shrink rather than refunding one", () => {
    // The case an operator is most likely to expect money back for. RP-1 halves
    // both sides of the difference and charges the result.
    const down = MODIFY_CASES.cases.find((c) => c.isDowngrade);
    expect(down).toBeDefined();
    expect(down?.total).toBeGreaterThan(0);
  });

  it("refuses to quote a renovation that changes the complex's fluids", () => {
    /*
     * RP-1 prices the resource difference at 0.6 of a fresh tank and a reduction
     * at a tenth, and the per-unit figures the wire carries are for a PAD build
     * rather than a renovation. A quote that dropped the difference would name a
     * renovation under its true cost.
     */
    const geometry = {
      humanRated: false,
      isHangar: false,
      massMax: 100,
      sizeMaxDepth: 10,
      sizeMaxHeight: 20,
      sizeMaxWidth: 10,
    };

    expect(
      quoteModifyComplex(
        { ...geometry, resources: new Map([["Kerosene", 2000]]) },
        {
          ...geometry,
          launchPadCount: 1,
          massOrig: 100,
          resources: new Map([["Kerosene", 1000]]),
        },
        { additionalPadCostMult: value("ratio", 0.5) },
      ),
    ).toBeNull();
  });

  it("refuses a multi-pad complex until RP-1 has said what an extra pad costs", () => {
    /*
     * A renovation reprices every pad the complex already has, so the
     * additional-pad multiplier is part of the price rather than a detail of
     * buying one. Absent is not 0.5: a career whose setting has been retuned
     * would be quoted against a figure RP-1 does not use, and this transcription
     * exists to agree with RP-1 rather than with its own defaults.
     */
    const geometry = {
      humanRated: false,
      isHangar: false,
      resources: new Map<string, number>(),
      sizeMaxDepth: 10,
      sizeMaxHeight: 20,
      sizeMaxWidth: 10,
    };
    const current = { ...geometry, massMax: 100, massOrig: 100 };

    expect(
      quoteModifyComplex(
        { ...geometry, massMax: 180 },
        { ...current, launchPadCount: 2 },
        {},
      ),
    ).toBeNull();
    // One pad needs no multiplier at all, so the same career still gets a quote.
    expect(
      quoteModifyComplex(
        { ...geometry, massMax: 180 },
        { ...current, launchPadCount: 1 },
        {},
      ),
    ).not.toBeNull();
  });
});
