//     This code was generated by the Sitrep contract command-map codegen
//     (Sitrep.Contract.RtConfig.EmitCommandMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// Derived by reflecting over every [SitrepCommand]-tagged args type: the
// attribute's CommandId is the map key, the tagged type's generated interface
// is the args, and the attribute's Payload/Result decides what the dispatch
// resolves with. One args type carries several tags where one shape serves
// several commands, which is why the reflection is over ATTRIBUTES rather
// than over types.
//
// WHAT THE COUNT COUNTS, because a grep gets it wrong. It is one entry per
// [SitrepCommand] ATTRIBUTE, not per tagged type: SetEnabledArgs alone carries
// six. Counting `AddCommandHandler` call sites instead misses the ones the
// engine registers directly; counting `const string \w*Command\w*` catches
// CommandCentreTopic, which is a Topic; counting the strings the bundled
// clients dispatch counts what a widget presses today rather than what the
// mod accepts, and gets a quarter of the answer. Read this file.
//
// THE TOPIC MAP'S DYNAMIC CAVEAT DOES NOT CARRY OVER. There is no such
// thing as a dynamic command. `AddCommandHandler` and
// `AddVantageCommandHandler` both refuse a command with no matching
// `CommandDeclaration` in the registering uplink's Manifest, and
// `ChannelEngine` dispatches by exact dictionary key with no prefix
// matching anywhere, so a per-subject write cannot BE a command id.
//
// The subject travels in the ARGS instead, which is the fact an author
// needs: `vessel.invokePartAction` is ONE command taking a `partId`, not one
// command per part, and `science.experiment.deploy` is one taking a
// `partId`, not one per instrument. A widget composes a topic string per
// subject and never composes a command string. An Uplink's own commands
// work the same way; see that Uplink's map for its examples.
//
// So every command a client can send is nameable before the game is running,
// and this map is that set as far as the [SitrepCommand] reflection reaches.
// What it does NOT prove is that every declared command is tagged: nothing
// checks a Manifest's `Command(...)` entries against the attributes, so one
// declared and handled without a tag would be dispatchable and absent here.
//
// An earlier version of this header said the opposite of all of it, in
// arithmetic: that the count excluded a number "per CPU, per vessel, per
// compute topic". That described a mechanism which has never existed, and
// was inherited from the topic map's caveat, where it is real.

import type {
  KosKeystrokeArgs,
  KosRunArgs,
  KosTerminalCloseArgs,
  KosTerminalOpenArgs,
  KosTerminalResizeArgs,
} from "./contract.js";
import type {
  CommandResult,
} from "@ksp-gonogo/sitrep-sdk";

export interface GeneratedCommandArgsMap {
  "kos.keystroke": KosKeystrokeArgs;
  "kos.run": KosRunArgs;
  "kos.terminal.close": KosTerminalCloseArgs;
  "kos.terminal.open": KosTerminalOpenArgs;
  "kos.terminal.resize": KosTerminalResizeArgs;
}

export interface GeneratedCommandReplyMap {
  "kos.keystroke": CommandResult;
  "kos.run": CommandResult;
  "kos.terminal.close": CommandResult;
  "kos.terminal.open": CommandResult;
  "kos.terminal.resize": CommandResult;
}

export const GENERATED_COMMAND_IDS = [
  "kos.keystroke",
  "kos.run",
  "kos.terminal.close",
  "kos.terminal.open",
  "kos.terminal.resize",
] as const;
