//     This code was generated by the Sitrep contract error-code codegen
//     (Sitrep.Contract.RtConfig.EmitErrorCodeMap, invoked from mod/codegen.sh).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import type { ErrorCodeDeclaration } from "@ksp-gonogo/sitrep-sdk";

/**
 * The refusals kOS's commands answer with that say more than a core code can:
 * each refines the root a client classifies it by.
 *
 * @category Error codes
 */
export const KosErrorCodes = {
  /**
   * Another screen holds this CPU's terminal. A terminal is leased to one screen
   * at a time and never taken from it; it frees when that screen closes it.
   */
  TerminalHeld: "kos.terminalHeld",
  /**
   * The CPU is booting, running a program, or already running a script for
   * another request, so it is not at a prompt that can take one.
   */
  CpuBusy: "kos.cpuBusy",
  /**
   * The CPU has no terminal window a script could be typed into.
   */
  NoTerminal: "kos.noTerminal",
} as const;
export type KosErrorCodes = (typeof KosErrorCodes)[keyof typeof KosErrorCodes];

/**
 * Every code declared here, with the sentence an operator reads for it.
 *
 * @category Error codes
 */
export const KOS_ERROR_CODES: readonly ErrorCodeDeclaration[] = [
  {
    id: "kos.terminalHeld",
    kind: "refusal",
    refines: "notClearToProceed",
    origin: null,
    sentence: "another screen is using this CPU's terminal",
    meaning: "Another screen holds this CPU's terminal. A terminal is leased to one screen at a time and never taken from it; it frees when that screen closes it.",
  },
  {
    id: "kos.cpuBusy",
    kind: "refusal",
    refines: "notClearToProceed",
    origin: null,
    sentence: "the CPU is busy and not at its prompt",
    meaning: "The CPU is booting, running a program, or already running a script for another request, so it is not at a prompt that can take one.",
  },
  {
    id: "kos.noTerminal",
    kind: "refusal",
    refines: "capabilityMismatch",
    origin: null,
    sentence: "that CPU has no terminal window to type into",
    meaning: "The CPU has no terminal window a script could be typed into.",
  },
];
