#!/usr/bin/env node
/**
 * Every Uplink's page: generated, and kept current by CI.
 *
 * An Uplink's README is DERIVED, from its registrations, its generated contract
 * slice, its fixtures and the one `uplink.md` its author writes. So it is
 * generated here rather than typed, for the reason every list in this repo is
 * discovered rather than listed: a hand-written page has no gate on its own
 * completeness, and it silently stops describing the Uplink the first time
 * somebody adds a widget and forgets.
 *
 * Three questions, and they are NOT the same:
 *
 *   --gate    does every client-bearing Uplink HAVE a generated page. Pure
 *             filesystem, a second, no browser
 *   --check   is each page CURRENT. Renders every widget in chromium
 *   (default)  regenerate them
 *
 * `--gate` is not implied by `--check`: a missing page is not a stale page, and
 * until this landed the example Uplink had no page at all while CI reported
 * green, because its `docs:check` was asked whether a page it did not have had
 * drifted.
 *
 * ## Why the check exists alongside the regenerate-on-main workflow
 *
 * `.github/workflows/uplink-docs.yml` runs the regenerate on a push to main and
 * commits the result back, so main heals itself. That is exactly why the check
 * has to exist too: a workflow that silently fixes main means nobody ever sees a
 * generator that has quietly stopped emitting a section. The self-heal keeps the
 * pages right; the check keeps the SIGNAL, on the pull request, where a person is
 * looking.
 *
 * Usage:
 *   node tooling/uplink-docs.mjs                    regenerate every page
 *   node tooling/uplink-docs.mjs --check            fail on any page that drifted
 *   node tooling/uplink-docs.mjs --gate             fail on any Uplink with no page
 *   node tooling/uplink-docs.mjs --check --only <name>   one Uplink, for a CI leg
 *
 * `--only` exists so a per-Uplink CI leg can run this rather than the CLI
 * directly, and still get `RENDER_DEBT` applied. A leg calling
 * `gonogo-uplink docs --check` itself would be permanently red for an Uplink
 * whose render is known-broken, and a permanently-red leg hides the next real
 * failure behind it.
 */

import { execFileSync, spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const mode = args.includes("--gate")
  ? "gate"
  : args.includes("--check")
    ? "check"
    : "write";

/**
 * Uplinks whose page cannot currently be REGENERATED. SHRINK ONLY.
 *
 * Not an excuse from having a page (that is `--gate`, and its list is empty):
 * these have one, and the render that would rebuild it fails for a reason inside
 * the Uplink rather than in the generator. Listed rather than left red, because
 * this repo's rule is that a permanently-failing leg hides the next real failure
 * behind it.
 *
 * Each entry states the failure. Delete it when the render passes; an entry that
 * passes fails as STALE, because a debt list nobody prunes stops describing
 * anything.
 */
const RENDER_DEBT = new Map([
  [
    "scansat",
    // `kerbin-partial-scan` emits `scansat.scanningVessels` and nothing in the
    // mounted tree subscribes to it, so the harness refuses the scene. The
    // caption says "one satellite with sensors in range", and the topic is read
    // by `FootprintOverlay` rather than by `Scanning`, so the scene intends an
    // overlay it is not composing. Deleting the emit would make the render pass
    // and silently drop the scene's stated subject, which is the wrong fix: the
    // question is why the overlay is not mounted.
    "kerbin-partial-scan: scansat.scanningVessels is emitted and nothing subscribes",
  ],
]);

/** The banner `gonogo-uplink docs` writes as a page's first line. */
const GENERATED_BANNER = "<!-- Generated by `gonogo-uplink docs`";

/**
 * What one Uplink's client directory is missing, as a list of reasons. Empty
 * means it has a page.
 *
 * A pure function of a directory, so the self-check below can run it against a
 * planted tree. A predicate that can only be run against the real repo cannot be
 * shown to fail, and a check that cannot fail reports success.
 */
export function missingPageReasons(clientDir) {
  const reasons = [];
  const prose = join(clientDir, "uplink.md");
  if (!existsSync(prose)) {
    reasons.push("no uplink.md (the one file the author writes)");
  } else if (readFileSync(prose, "utf8").trim().length === 0) {
    reasons.push("uplink.md is empty");
  }

  const readme = join(clientDir, "README.md");
  if (!existsSync(readme)) {
    reasons.push("no README.md");
  } else if (!readFileSync(readme, "utf8").startsWith(GENERATED_BANNER)) {
    reasons.push("README.md was not generated (no generator banner on line 1)");
  }

  if (!existsSync(join(clientDir, "gonogo-uplink.json"))) {
    reasons.push("no gonogo-uplink.json");
  }
  return reasons;
}

/**
 * Prove the predicate can see a missing page before trusting it about the real
 * Uplinks.
 *
 * Three planted trees, because the ways a page goes missing are not one shape:
 * nothing there at all, a hand-written README, and a complete page, which must
 * come back CLEAN or the gate is failing everything and a pass means nothing.
 */
function selfCheck() {
  const dir = mkdtempSync(join(tmpdir(), "uplink-docs-gate-"));
  try {
    const tree = (name, files) => {
      const at = join(dir, name);
      mkdirSync(at, { recursive: true });
      for (const [file, body] of Object.entries(files)) {
        writeFileSync(join(at, file), body);
      }
      return at;
    };
    const complete = {
      "uplink.md": "A real lede.\n",
      "README.md": `${GENERATED_BANNER} -->\n\n# Some Uplink\n`,
      "gonogo-uplink.json": "{}\n",
    };

    const faults = [];
    const bare = missingPageReasons(tree("bare", {}));
    if (bare.length !== 3) {
      faults.push(
        `an empty client directory should be missing all three things, and this reported ${bare.length}`,
      );
    }
    const handWritten = missingPageReasons(
      tree("hand-written", {
        ...complete,
        "README.md": "# Some Uplink\n\nWritten by a person.\n",
      }),
    );
    if (!handWritten.some((r) => r.includes("not generated"))) {
      faults.push(
        "a hand-written README passed, so this cannot tell a generated page from a typed one",
      );
    }
    const generated = missingPageReasons(tree("generated", complete));
    if (generated.length !== 0) {
      faults.push(
        `a complete generated page was reported as missing: ${generated.join("; ")}`,
      );
    }

    if (faults.length > 0) {
      console.error(
        "✖ this cannot see its own failure, so its verdict about the real Uplinks means\n" +
          "  nothing:\n" +
          faults.map((f) => `    ${f}`).join("\n"),
      );
      process.exit(1);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * Discovered from the same matrix CI iterates, never a list here. An Uplink
 * missing from a hand-kept list is an Uplink this never checks, reported as a
 * clean pass.
 */
const discovered = JSON.parse(
  execFileSync("node", [join(ROOT, "scripts/uplink-matrix.mjs")], {
    encoding: "utf8",
  }),
).filter((leg) => leg.client);

if (discovered.length === 0) {
  console.error(
    "✖ the matrix reported no Uplink with a client, so this examined nothing and would have\n" +
      "  exited clean. Discovery is broken rather than the repo being empty.",
  );
  process.exit(1);
}

const only = args.includes("--only")
  ? args[args.indexOf("--only") + 1]
  : undefined;
const legs = only
  ? discovered.filter((leg) => leg.name === only)
  : discovered;

// A `--only` that matches nothing is a typo in a workflow, and it would examine
// nothing and exit clean, which is the shape this whole file is against.
if (legs.length === 0) {
  console.error(
    `✖ --only ${only} matches no client-bearing Uplink. Known: ` +
      `${discovered.map((leg) => leg.name).join(", ")}`,
  );
  process.exit(1);
}

if (mode === "gate") {
  selfCheck();
  const rows = legs.map((leg) => ({
    name: leg.name,
    reasons: missingPageReasons(join(ROOT, "uplinks", leg.name, "client")),
  }));
  for (const row of rows) {
    console.log(
      `  ${(row.reasons.length === 0 ? "page" : "NO PAGE").padEnd(8)} ${row.name.padEnd(20)} ${row.reasons.join("; ")}`,
    );
  }
  const without = rows.filter((row) => row.reasons.length > 0);
  if (without.length > 0) {
    console.error(
      `\n✖ ${without.length} client-bearing Uplink(s) have no generated page:\n` +
        without.map((r) => `    ${r.name}: ${r.reasons.join("; ")}`).join("\n") +
        "\n\n  The page is generated from the registrations, the contract slice and the fixtures,\n" +
        "  so the only part to write is the prose. Create client/uplink.md with a lede and\n" +
        "  optional `## widget:<id>` sections, then run:\n" +
        "    node tooling/uplink-docs.mjs",
    );
    process.exit(1);
  }
  console.log(
    `\nall ${rows.length} client-bearing Uplink(s) have a generated page.`,
  );
  process.exit(0);
}

const verb = mode === "check" ? ["docs", "--check"] : ["docs"];
const failed = [];
const unexpectedPass = [];

for (const leg of legs) {
  /*
   * An excused Uplink is SKIPPED when writing, never run and excused.
   *
   * `docs` clears the asset directory before it renders, so a run that fails
   * part-way leaves the committed images DELETED. The regenerate workflow stages
   * asset deletions (a removed fixture is real drift), so running a
   * known-broken render there would have committed the removal of a working
   * page's pictures. `--check` renders into a temp directory and touches
   * nothing, which is why it still runs them and reports.
   */
  if (mode === "write" && RENDER_DEBT.has(leg.name)) {
    console.log(
      `── ${leg.name}: SKIPPED, in RENDER_DEBT (${RENDER_DEBT.get(leg.name)}).\n` +
        "   Its committed page is left exactly as it is: a failed render would " +
        "delete the images first.",
    );
    continue;
  }
  console.log(`── ${leg.name}`);
  const result = spawnSync("npm", ["exec", "--", "gonogo-uplink", ...verb], {
    cwd: join(ROOT, "uplinks", leg.name, "client"),
    stdio: "inherit",
  });
  const ok = result.status === 0;
  if (!ok && !RENDER_DEBT.has(leg.name)) failed.push(leg.name);
  if (ok && RENDER_DEBT.has(leg.name)) unexpectedPass.push(leg.name);
  if (!ok && RENDER_DEBT.has(leg.name)) {
    console.log(`   excused by RENDER_DEBT: ${RENDER_DEBT.get(leg.name)}`);
  }
}

// Both directions, like every other ratchet here.
if (unexpectedPass.length > 0) {
  console.error(
    `\n✖ ${unexpectedPass.length} Uplink(s) now render and are still in RENDER_DEBT:\n` +
      unexpectedPass.map((n) => `    ${n}`).join("\n") +
      "\n\n  Delete those entries from tooling/uplink-docs.mjs to ratchet the gate down.",
  );
  process.exit(1);
}

if (failed.length > 0) {
  console.error(
    `\n✖ ${failed.length} of ${legs.length} Uplink page(s) ` +
      `${mode === "check" ? "no longer describe the code" : "could not be generated"}:\n` +
      failed.map((n) => `    ${n}`).join("\n") +
      (mode === "check"
        ? "\n\n  Regenerate and commit the result. The page is derived, so the fix is never to\n" +
          "  edit it:\n    node tooling/uplink-docs.mjs"
        : ""),
  );
  process.exit(1);
}

const excused = legs.filter((leg) => RENDER_DEBT.has(leg.name)).length;
console.log(
  mode === "check"
    ? `\nall ${legs.length} Uplink page(s) match the code` +
        `${excused > 0 ? `; ${excused} render failure(s) excused by RENDER_DEBT` : ""}.`
    : `\n${legs.length - excused} Uplink page(s) regenerated` +
        `${excused > 0 ? `; ${excused} skipped, in RENDER_DEBT` : ""}.`,
);
